# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
schemas/openapi.json:
  info-license:
    - '#/info'
  operation-4xx-response:
    - '#/paths/~1private~1change_subaccount_label/post/responses'
    - '#/paths/~1private~1get_all_portfolios/post/responses'
    - '#/paths/~1private~1get_collaterals/post/responses'
    - '#/paths/~1private~1get_positions/post/responses'
    - '#/paths/~1private~1get_subaccount/post/responses'
    - '#/paths/~1private~1get_subaccounts/post/responses'
    - '#/paths/~1private~1create_session_key/post/responses'
    - '#/paths/~1private~1edit_session_key/post/responses'
    - '#/paths/~1private~1session_keys/post/responses'
    - '#/paths/~1public~1get_wallets_from_session_key/post/responses'
    - '#/paths/~1private~1get_account/post/responses'
    - '#/paths/~1private~1cancel/post/responses'
    - '#/paths/~1private~1cancel_algo_order/post/responses'
    - '#/paths/~1private~1cancel_all/post/responses'
    - '#/paths/~1private~1cancel_all_algo_orders/post/responses'
    - '#/paths/~1private~1cancel_all_trigger_orders/post/responses'
    - '#/paths/~1private~1cancel_by_instrument/post/responses'
    - '#/paths/~1private~1cancel_by_label/post/responses'
    - '#/paths/~1private~1cancel_by_nonce/post/responses'
    - '#/paths/~1private~1cancel_trigger_order/post/responses'
    - '#/paths/~1private~1get_algo_orders/post/responses'
    - '#/paths/~1private~1get_open_orders/post/responses'
    - '#/paths/~1private~1get_order/post/responses'
    - '#/paths/~1private~1get_trigger_orders/post/responses'
    - '#/paths/~1private~1order/post/responses'
    - '#/paths/~1private~1order_debug/post/responses'
    - '#/paths/~1private~1order_quote/post/responses'
    - '#/paths/~1private~1replace/post/responses'
    - '#/paths/~1public~1order_quote/post/responses'
    - '#/paths/~1private~1cancel_batch_quotes/post/responses'
    - '#/paths/~1private~1cancel_batch_rfqs/post/responses'
    - '#/paths/~1private~1cancel_quote/post/responses'
    - '#/paths/~1private~1cancel_rfq/post/responses'
    - '#/paths/~1private~1execute_quote/post/responses'
    - '#/paths/~1private~1get_quotes/post/responses'
    - '#/paths/~1private~1get_rfqs/post/responses'
    - '#/paths/~1private~1poll_quotes/post/responses'
    - '#/paths/~1private~1poll_rfqs/post/responses'
    - '#/paths/~1private~1replace_quote/post/responses'
    - '#/paths/~1private~1rfq_get_best_quote/post/responses'
    - '#/paths/~1private~1send_quote/post/responses'
    - '#/paths/~1private~1send_rfq/post/responses'
    - '#/paths/~1public~1execute_quote_debug/post/responses'
    - '#/paths/~1public~1send_quote_debug/post/responses'
    - '#/paths/~1private~1cancel_all_vault_requests/post/responses'
    - '#/paths/~1private~1get_live_vault_requests/post/responses'
    - '#/paths/~1private~1get_shareholder_vaults/post/responses'
    - '#/paths/~1private~1get_vault_request_history/post/responses'
    - '#/paths/~1private~1get_vault_shares/post/responses'
    - '#/paths/~1private~1request_vault_deposit/post/responses'
    - '#/paths/~1private~1request_vault_withdraw/post/responses'
    - '#/paths/~1public~1get_vault/post/responses'
    - '#/paths/~1public~1get_vault_action_history/post/responses'
    - '#/paths/~1public~1get_vault_performance_history/post/responses'
    - '#/paths/~1public~1get_vaults/post/responses'
    - '#/paths/~1private~1burn_vault_shares/post/responses'
    - '#/paths/~1private~1create_vault/post/responses'
    - '#/paths/~1private~1force_burn/post/responses'
    - '#/paths/~1private~1get_curated_vaults/post/responses'
    - '#/paths/~1private~1get_live_burn_requests/post/responses'
    - '#/paths/~1private~1get_live_mint_requests/post/responses'
    - '#/paths/~1private~1mint_vault_shares/post/responses'
    - '#/paths/~1private~1reject_deposit_request/post/responses'
    - '#/paths/~1private~1update_vault_info/post/responses'
    - '#/paths/~1private~1get_deposit_history/post/responses'
    - '#/paths/~1private~1get_erc20_transfer_history/post/responses'
    - '#/paths/~1private~1get_funding_history/post/responses'
    - '#/paths/~1private~1get_interest_history/post/responses'
    - '#/paths/~1private~1get_option_settlement_history/post/responses'
    - '#/paths/~1private~1get_order_history/post/responses'
    - '#/paths/~1private~1get_trade_history/post/responses'
    - '#/paths/~1private~1get_withdrawal_history/post/responses'
    - '#/paths/~1private~1get_mmp_config/post/responses'
    - '#/paths/~1private~1reset_mmp/post/responses'
    - '#/paths/~1private~1set_mmp_config/post/responses'
    - '#/paths/~1private~1transfer_positions/post/responses'
    - '#/paths/~1private~1transfer_spot/post/responses'
    - '#/paths/~1private~1transfer_spot_external/post/responses'
    - '#/paths/~1private~1update_whitelisted_recipients/post/responses'
    - '#/paths/~1private~1withdraw/post/responses'
    - '#/paths/~1public~1withdraw_debug/post/responses'
    - '#/paths/~1public~1get_onchain_action_history/post/responses'
    - '#/paths/~1public~1get_pending_deposits/post/responses'
    - '#/paths/~1public~1register_deposit_address/post/responses'
    - '#/paths/~1public~1getRateLimits/post/responses'
    - '#/paths/~1public~1get_time/post/responses'
    - '#/paths/~1public~1get_transaction/post/responses'
    - '#/paths/~1public~1get_all_currencies/post/responses'
    - '#/paths/~1public~1get_all_instruments/post/responses'
    - '#/paths/~1public~1get_all_live_instruments/post/responses'
    - '#/paths/~1public~1get_assets/post/responses'
    - '#/paths/~1public~1get_currency/post/responses'
    - '#/paths/~1public~1get_funding_rate_history/post/responses'
    - '#/paths/~1public~1get_index_chart_data/post/responses'
    - '#/paths/~1public~1get_instrument/post/responses'
    - '#/paths/~1public~1get_interest_rate_history/post/responses'
    - '#/paths/~1public~1get_latest_signed_feeds/post/responses'
    - '#/paths/~1public~1get_option_settlement_prices/post/responses'
    - '#/paths/~1public~1get_risk_universes/post/responses'
    - '#/paths/~1public~1get_ticker/post/responses'
    - '#/paths/~1public~1get_tickers/post/responses'
    - '#/paths/~1public~1get_trade_history/post/responses'
    - '#/paths/~1public~1get_tradingview_chart_data/post/responses'
    - '#/paths/~1public~1get_all_referral_codes/post/responses'
    - '#/paths/~1public~1get_referral_performance/post/responses'
  security-defined:
    - '#/paths/~1private~1change_subaccount_label/post'
    - '#/paths/~1private~1get_all_portfolios/post'
    - '#/paths/~1private~1get_collaterals/post'
    - '#/paths/~1private~1get_positions/post'
    - '#/paths/~1private~1get_subaccount/post'
    - '#/paths/~1private~1get_subaccounts/post'
    - '#/paths/~1private~1create_session_key/post'
    - '#/paths/~1private~1edit_session_key/post'
    - '#/paths/~1private~1session_keys/post'
    - '#/paths/~1public~1get_wallets_from_session_key/post'
    - '#/paths/~1private~1get_account/post'
    - '#/paths/~1private~1cancel/post'
    - '#/paths/~1private~1cancel_algo_order/post'
    - '#/paths/~1private~1cancel_all/post'
    - '#/paths/~1private~1cancel_all_algo_orders/post'
    - '#/paths/~1private~1cancel_all_trigger_orders/post'
    - '#/paths/~1private~1cancel_by_instrument/post'
    - '#/paths/~1private~1cancel_by_label/post'
    - '#/paths/~1private~1cancel_by_nonce/post'
    - '#/paths/~1private~1cancel_trigger_order/post'
    - '#/paths/~1private~1get_algo_orders/post'
    - '#/paths/~1private~1get_open_orders/post'
    - '#/paths/~1private~1get_order/post'
    - '#/paths/~1private~1get_trigger_orders/post'
    - '#/paths/~1private~1order/post'
    - '#/paths/~1private~1order_debug/post'
    - '#/paths/~1private~1order_quote/post'
    - '#/paths/~1private~1replace/post'
    - '#/paths/~1public~1order_quote/post'
    - '#/paths/~1private~1cancel_batch_quotes/post'
    - '#/paths/~1private~1cancel_batch_rfqs/post'
    - '#/paths/~1private~1cancel_quote/post'
    - '#/paths/~1private~1cancel_rfq/post'
    - '#/paths/~1private~1execute_quote/post'
    - '#/paths/~1private~1get_quotes/post'
    - '#/paths/~1private~1get_rfqs/post'
    - '#/paths/~1private~1poll_quotes/post'
    - '#/paths/~1private~1poll_rfqs/post'
    - '#/paths/~1private~1replace_quote/post'
    - '#/paths/~1private~1rfq_get_best_quote/post'
    - '#/paths/~1private~1send_quote/post'
    - '#/paths/~1private~1send_rfq/post'
    - '#/paths/~1public~1execute_quote_debug/post'
    - '#/paths/~1public~1send_quote_debug/post'
    - '#/paths/~1private~1cancel_all_vault_requests/post'
    - '#/paths/~1private~1get_live_vault_requests/post'
    - '#/paths/~1private~1get_shareholder_vaults/post'
    - '#/paths/~1private~1get_vault_request_history/post'
    - '#/paths/~1private~1get_vault_shares/post'
    - '#/paths/~1private~1request_vault_deposit/post'
    - '#/paths/~1private~1request_vault_withdraw/post'
    - '#/paths/~1public~1get_vault/post'
    - '#/paths/~1public~1get_vault_action_history/post'
    - '#/paths/~1public~1get_vault_performance_history/post'
    - '#/paths/~1public~1get_vaults/post'
    - '#/paths/~1private~1burn_vault_shares/post'
    - '#/paths/~1private~1create_vault/post'
    - '#/paths/~1private~1force_burn/post'
    - '#/paths/~1private~1get_curated_vaults/post'
    - '#/paths/~1private~1get_live_burn_requests/post'
    - '#/paths/~1private~1get_live_mint_requests/post'
    - '#/paths/~1private~1mint_vault_shares/post'
    - '#/paths/~1private~1reject_deposit_request/post'
    - '#/paths/~1private~1update_vault_info/post'
    - '#/paths/~1private~1get_deposit_history/post'
    - '#/paths/~1private~1get_erc20_transfer_history/post'
    - '#/paths/~1private~1get_funding_history/post'
    - '#/paths/~1private~1get_interest_history/post'
    - '#/paths/~1private~1get_option_settlement_history/post'
    - '#/paths/~1private~1get_order_history/post'
    - '#/paths/~1private~1get_trade_history/post'
    - '#/paths/~1private~1get_withdrawal_history/post'
    - '#/paths/~1private~1get_mmp_config/post'
    - '#/paths/~1private~1reset_mmp/post'
    - '#/paths/~1private~1set_mmp_config/post'
    - '#/paths/~1private~1transfer_positions/post'
    - '#/paths/~1private~1transfer_spot/post'
    - '#/paths/~1private~1transfer_spot_external/post'
    - '#/paths/~1private~1update_whitelisted_recipients/post'
    - '#/paths/~1private~1withdraw/post'
    - '#/paths/~1public~1withdraw_debug/post'
    - '#/paths/~1public~1get_onchain_action_history/post'
    - '#/paths/~1public~1get_pending_deposits/post'
    - '#/paths/~1public~1register_deposit_address/post'
    - '#/paths/~1public~1getRateLimits/post'
    - '#/paths/~1public~1get_time/post'
    - '#/paths/~1public~1get_transaction/post'
    - '#/paths/~1public~1get_all_currencies/post'
    - '#/paths/~1public~1get_all_instruments/post'
    - '#/paths/~1public~1get_all_live_instruments/post'
    - '#/paths/~1public~1get_assets/post'
    - '#/paths/~1public~1get_currency/post'
    - '#/paths/~1public~1get_funding_rate_history/post'
    - '#/paths/~1public~1get_index_chart_data/post'
    - '#/paths/~1public~1get_instrument/post'
    - '#/paths/~1public~1get_interest_rate_history/post'
    - '#/paths/~1public~1get_latest_signed_feeds/post'
    - '#/paths/~1public~1get_option_settlement_prices/post'
    - '#/paths/~1public~1get_risk_universes/post'
    - '#/paths/~1public~1get_ticker/post'
    - '#/paths/~1public~1get_tickers/post'
    - '#/paths/~1public~1get_trade_history/post'
    - '#/paths/~1public~1get_tradingview_chart_data/post'
    - '#/paths/~1public~1get_all_referral_codes/post'
    - '#/paths/~1public~1get_referral_performance/post'
