/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountFeeInfo {
    #[serde(rename = "base_fee_discount")]
    pub base_fee_discount: String,
    #[serde(rename = "option_maker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_maker_fee: Option<Option<String>>,
    #[serde(rename = "option_taker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_taker_fee: Option<Option<String>>,
    #[serde(rename = "perp_maker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub perp_maker_fee: Option<Option<String>>,
    #[serde(rename = "perp_taker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub perp_taker_fee: Option<Option<String>>,
    #[serde(rename = "rfq_maker_discount")]
    pub rfq_maker_discount: String,
    #[serde(rename = "rfq_taker_discount")]
    pub rfq_taker_discount: String,
    #[serde(rename = "spot_maker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spot_maker_fee: Option<Option<String>>,
    #[serde(rename = "spot_taker_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spot_taker_fee: Option<Option<String>>,
}

impl AccountFeeInfo {
    pub fn new(base_fee_discount: String, rfq_maker_discount: String, rfq_taker_discount: String) -> AccountFeeInfo {
        AccountFeeInfo {
            base_fee_discount,
            option_maker_fee: None,
            option_taker_fee: None,
            perp_maker_fee: None,
            perp_taker_fee: None,
            rfq_maker_discount,
            rfq_taker_discount,
            spot_maker_fee: None,
            spot_taker_fee: None,
        }
    }
}

