/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Action : EIP-712 typed-data Action struct that you sign; its fields are defined below.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// ABI-encoded action data (`bytes`).
    #[serde(rename = "data")]
    pub data: Vec<i32>,
    /// Unix timestamp after which the action is invalid (`uint256`).
    #[serde(rename = "expiry")]
    pub expiry: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "module")]
    pub module: String,
    /// Replay-protection nonce (`uint256`), interpreted as a UTC-**nanosecond** timestamp: it must fall within the nonce validity window (one day) of the action's timestamp.
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "owner")]
    pub owner: String,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    /// Subaccount identifier (`uint256`).
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl Action {
    /// EIP-712 typed-data Action struct that you sign; its fields are defined below.
    pub fn new(data: Vec<i32>, expiry: i32, module: String, nonce: i32, owner: String, signer: String, subaccount_id: i32) -> Action {
        Action {
            data,
            expiry,
            module,
            nonce,
            owner,
            signer,
            subaccount_id,
        }
    }
}

