/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetType : Asset type of the instrument: `\"option\"`, `\"perp\"`, or `\"erc20\"`.
/// Asset type of the instrument: `\"option\"`, `\"perp\"`, or `\"erc20\"`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetType {
    #[serde(rename = "option")]
    Option,
    #[serde(rename = "perp")]
    Perp,
    #[serde(rename = "erc20")]
    Erc20,

}

impl std::fmt::Display for AssetType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Option => write!(f, "option"),
            Self::Perp => write!(f, "perp"),
            Self::Erc20 => write!(f, "erc20"),
        }
    }
}

impl Default for AssetType {
    fn default() -> AssetType {
        Self::Option
    }
}

