/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetEntry : A non-spot asset (option or perp) and its per-universe risk.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetEntry {
    /// EIP-55 checksummed protocol asset address.
    #[serde(rename = "address")]
    pub address: String,
    /// Registered asset name (e.g. \"ETH-OPTION\", \"ETH-PERP\").
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "universes")]
    pub universes: Vec<models::AssetUniverse>,
}

impl AssetEntry {
    /// A non-spot asset (option or perp) and its per-universe risk.
    pub fn new(address: String, name: String, universes: Vec<models::AssetUniverse>) -> AssetEntry {
        AssetEntry {
            address,
            name,
            universes,
        }
    }
}

