/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetUniverse : Per-`(asset, universe)` open interest for an option/perp asset.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetUniverse {
    #[serde(rename = "oi")]
    pub oi: models::OpenInterestStats,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    /// Display name of the universe (uppercase, e.g. \"PRIME\"); absent until set by the exchange.
    #[serde(rename = "risk_universe_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_universe_name: Option<Option<String>>,
}

impl AssetUniverse {
    /// Per-`(asset, universe)` open interest for an option/perp asset.
    pub fn new(oi: models::OpenInterestStats, risk_universe_id: i32) -> AssetUniverse {
        AssetUniverse {
            oi,
            risk_universe_id,
            risk_universe_name: None,
        }
    }
}

