/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "asset_id")]
    pub asset_id: String,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    #[serde(rename = "asset_type")]
    pub asset_type: models::AssetType,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "erc20_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub erc20_details: Option<Option<models::Erc20Details>>,
    #[serde(rename = "is_collateral")]
    pub is_collateral: bool,
    #[serde(rename = "is_position")]
    pub is_position: bool,
    #[serde(rename = "option_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_details: Option<Option<models::OptionDetails>>,
    #[serde(rename = "perp_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub perp_details: Option<Option<models::PerpDetails>>,
    #[serde(rename = "sub_id")]
    pub sub_id: String,
}

impl Asset {
    pub fn new(address: String, asset_id: String, asset_name: String, asset_type: models::AssetType, currency: String, is_collateral: bool, is_position: bool, sub_id: String) -> Asset {
        Asset {
            address,
            asset_id,
            asset_name,
            asset_type,
            currency,
            erc20_details: None,
            is_collateral,
            is_position,
            option_details: None,
            perp_details: None,
            sub_id,
        }
    }
}

