/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchStatus : Batch lifecycle status — the single source of lifecycle truth for every operation in the batch (individual ops carry no status of their own). Each stage has a healthy variant and a corresponding `...Error` variant meaning that stage failed. Serialized as the variant name (string) in API responses.
/// Batch lifecycle status — the single source of lifecycle truth for every operation in the batch (individual ops carry no status of their own). Each stage has a healthy variant and a corresponding `...Error` variant meaning that stage failed. Serialized as the variant name (string) in API responses.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BatchStatus {
    #[serde(rename = "Batching")]
    Batching,
    #[serde(rename = "Executing")]
    Executing,
    #[serde(rename = "Proving")]
    Proving,
    #[serde(rename = "Settling")]
    Settling,
    #[serde(rename = "Settled")]
    Settled,
    #[serde(rename = "BatchingError")]
    BatchingError,
    #[serde(rename = "ExecutingError")]
    ExecutingError,
    #[serde(rename = "ProvingError")]
    ProvingError,
    #[serde(rename = "SettlingError")]
    SettlingError,
    #[serde(rename = "SettledError")]
    SettledError,

}

impl std::fmt::Display for BatchStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Batching => write!(f, "Batching"),
            Self::Executing => write!(f, "Executing"),
            Self::Proving => write!(f, "Proving"),
            Self::Settling => write!(f, "Settling"),
            Self::Settled => write!(f, "Settled"),
            Self::BatchingError => write!(f, "BatchingError"),
            Self::ExecutingError => write!(f, "ExecutingError"),
            Self::ProvingError => write!(f, "ProvingError"),
            Self::SettlingError => write!(f, "SettlingError"),
            Self::SettledError => write!(f, "SettledError"),
        }
    }
}

impl Default for BatchStatus {
    fn default() -> BatchStatus {
        Self::Batching
    }
}

