/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelBatchRfqsResponse {
    #[serde(rename = "cancelled_ids")]
    pub cancelled_ids: Vec<uuid::Uuid>,
}

impl CancelBatchRfqsResponse {
    pub fn new(cancelled_ids: Vec<uuid::Uuid>) -> CancelBatchRfqsResponse {
        CancelBatchRfqsResponse {
            cancelled_ids,
        }
    }
}

