/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelRfqRequest {
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl CancelRfqRequest {
    pub fn new(rfq_id: uuid::Uuid, subaccount_id: i32) -> CancelRfqRequest {
        CancelRfqRequest {
            rfq_id,
            subaccount_id,
        }
    }
}

