/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelByLabelRequest {
    #[serde(rename = "instrument_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<Option<String>>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl CancelByLabelRequest {
    pub fn new(label: String, subaccount_id: i64) -> CancelByLabelRequest {
        CancelByLabelRequest {
            instrument_name: None,
            label,
            subaccount_id,
        }
    }
}

