/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CancelReason {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "user_request")]
    UserRequest,
    #[serde(rename = "mmp_trigger")]
    MmpTrigger,
    #[serde(rename = "insufficient_margin")]
    InsufficientMargin,
    #[serde(rename = "signed_max_fee_too_low")]
    SignedMaxFeeTooLow,
    #[serde(rename = "cancel_on_disconnect")]
    CancelOnDisconnect,
    #[serde(rename = "ioc_or_market_partial_fill")]
    IocOrMarketPartialFill,
    #[serde(rename = "session_key_deregistered")]
    SessionKeyDeregistered,
    #[serde(rename = "subaccount_withdrawn")]
    SubaccountWithdrawn,
    #[serde(rename = "compliance")]
    Compliance,
    #[serde(rename = "trigger_failed")]
    TriggerFailed,
    #[serde(rename = "validation_failed")]
    ValidationFailed,
    #[serde(rename = "algo_completed")]
    AlgoCompleted,

}

impl std::fmt::Display for CancelReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, ""),
            Self::UserRequest => write!(f, "user_request"),
            Self::MmpTrigger => write!(f, "mmp_trigger"),
            Self::InsufficientMargin => write!(f, "insufficient_margin"),
            Self::SignedMaxFeeTooLow => write!(f, "signed_max_fee_too_low"),
            Self::CancelOnDisconnect => write!(f, "cancel_on_disconnect"),
            Self::IocOrMarketPartialFill => write!(f, "ioc_or_market_partial_fill"),
            Self::SessionKeyDeregistered => write!(f, "session_key_deregistered"),
            Self::SubaccountWithdrawn => write!(f, "subaccount_withdrawn"),
            Self::Compliance => write!(f, "compliance"),
            Self::TriggerFailed => write!(f, "trigger_failed"),
            Self::ValidationFailed => write!(f, "validation_failed"),
            Self::AlgoCompleted => write!(f, "algo_completed"),
        }
    }
}

impl Default for CancelReason {
    fn default() -> CancelReason {
        Self::Empty
    }
}

