/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelByNonceResponse {
    #[serde(rename = "cancelled_orders")]
    pub cancelled_orders: i64,
}

impl CancelByNonceResponse {
    pub fn new(cancelled_orders: i64) -> CancelByNonceResponse {
        CancelByNonceResponse {
            cancelled_orders,
        }
    }
}

