/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelByInstrumentRequest {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl CancelByInstrumentRequest {
    pub fn new(instrument_name: String, subaccount_id: i64) -> CancelByInstrumentRequest {
        CancelByInstrumentRequest {
            instrument_name,
            subaccount_id,
        }
    }
}

