/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelBatchQuotesRequest {
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<serde_json::Value>>,
    #[serde(rename = "nonce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<Option<serde_json::Value>>,
    /// Optional UUID v4 string
    #[serde(rename = "quote_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<Option<uuid::Uuid>>,
    /// Optional UUID v4 string
    #[serde(rename = "rfq_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rfq_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl CancelBatchQuotesRequest {
    pub fn new(subaccount_id: i32) -> CancelBatchQuotesRequest {
        CancelBatchQuotesRequest {
            label: None,
            nonce: None,
            quote_id: None,
            rfq_id: None,
            subaccount_id,
        }
    }
}

