/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelAllRequest {
    #[serde(rename = "cancel_algo_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_algo_orders: Option<Option<bool>>,
    #[serde(rename = "cancel_trigger_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_trigger_orders: Option<Option<bool>>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl CancelAllRequest {
    pub fn new(subaccount_id: i64) -> CancelAllRequest {
        CancelAllRequest {
            cancel_algo_orders: None,
            cancel_trigger_orders: None,
            subaccount_id,
        }
    }
}

