/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelAllAlgoOrdersRequest {
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl CancelAllAlgoOrdersRequest {
    pub fn new(subaccount_id: i64) -> CancelAllAlgoOrdersRequest {
        CancelAllAlgoOrdersRequest {
            subaccount_id,
        }
    }
}

