/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeSubaccountLabelRequest {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl ChangeSubaccountLabelRequest {
    pub fn new(label: String, subaccount_id: i32) -> ChangeSubaccountLabelRequest {
        ChangeSubaccountLabelRequest {
            label,
            subaccount_id,
        }
    }
}

