/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collateral {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "amount_step")]
    pub amount_step: String,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    #[serde(rename = "asset_type")]
    pub asset_type: String,
    #[serde(rename = "average_price")]
    pub average_price: String,
    #[serde(rename = "average_price_excl_fees")]
    pub average_price_excl_fees: String,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "cumulative_interest")]
    pub cumulative_interest: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "delta")]
    pub delta: String,
    #[serde(rename = "delta_currency")]
    pub delta_currency: String,
    #[serde(rename = "initial_margin")]
    pub initial_margin: String,
    #[serde(rename = "maintenance_margin")]
    pub maintenance_margin: String,
    #[serde(rename = "mark_price")]
    pub mark_price: String,
    #[serde(rename = "mark_value")]
    pub mark_value: String,
    #[serde(rename = "open_orders_margin")]
    pub open_orders_margin: String,
    #[serde(rename = "pending_interest")]
    pub pending_interest: String,
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: String,
    #[serde(rename = "realized_pnl_excl_fees")]
    pub realized_pnl_excl_fees: String,
    #[serde(rename = "total_fees")]
    pub total_fees: String,
    #[serde(rename = "unrealized_pnl")]
    pub unrealized_pnl: String,
    #[serde(rename = "unrealized_pnl_excl_fees")]
    pub unrealized_pnl_excl_fees: String,
}

impl Collateral {
    pub fn new(amount: String, amount_step: String, asset_name: String, asset_type: String, average_price: String, average_price_excl_fees: String, creation_timestamp: i64, cumulative_interest: String, currency: String, delta: String, delta_currency: String, initial_margin: String, maintenance_margin: String, mark_price: String, mark_value: String, open_orders_margin: String, pending_interest: String, realized_pnl: String, realized_pnl_excl_fees: String, total_fees: String, unrealized_pnl: String, unrealized_pnl_excl_fees: String) -> Collateral {
        Collateral {
            amount,
            amount_step,
            asset_name,
            asset_type,
            average_price,
            average_price_excl_fees,
            creation_timestamp,
            cumulative_interest,
            currency,
            delta,
            delta_currency,
            initial_margin,
            maintenance_margin,
            mark_price,
            mark_value,
            open_orders_margin,
            pending_interest,
            realized_pnl,
            realized_pnl_excl_fees,
            total_fees,
            unrealized_pnl,
            unrealized_pnl_excl_fees,
        }
    }
}

