/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSessionKeyRequest : Request parameters for registering a scoped session key. Address fields are 0x-prefixed hex strings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionKeyRequest {
    #[serde(rename = "expiry_sec")]
    pub expiry_sec: i32,
    #[serde(rename = "ip_whitelist", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_whitelist: Option<Option<Vec<String>>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "nonce")]
    pub nonce: String,
    /// Off-chain scopes which are validated in backend only
    #[serde(rename = "offchain_scopes")]
    pub offchain_scopes: Vec<String>,
    /// Scopes granted to the session key, validated by the protocol. Each is a string like `\"trade:orderbook:all\"`.
    #[serde(rename = "protocol_scopes")]
    pub protocol_scopes: Vec<String>,
    /// Session key address being authorized.
    #[serde(rename = "public_session_key")]
    pub public_session_key: String,
    /// 0x-prefixed hex, 65-byte r||s||v.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_ids: Option<Option<Vec<i32>>>,
    /// Wallet the session key is being registered for.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl CreateSessionKeyRequest {
    /// Request parameters for registering a scoped session key. Address fields are 0x-prefixed hex strings.
    pub fn new(expiry_sec: i32, nonce: String, offchain_scopes: Vec<String>, protocol_scopes: Vec<String>, public_session_key: String, signature: String, signature_expiry_sec: i32, signer: String, wallet: String) -> CreateSessionKeyRequest {
        CreateSessionKeyRequest {
            expiry_sec,
            ip_whitelist: None,
            label: None,
            nonce,
            offchain_scopes,
            protocol_scopes,
            public_session_key,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_ids: None,
            wallet,
        }
    }
}

