/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateVaultRequest : Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVaultRequest {
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "benchmark_asset", skip_serializing_if = "Option::is_none")]
    pub benchmark_asset: Option<String>,
    #[serde(rename = "cooldown_sec")]
    pub cooldown_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "deposit_spot_asset")]
    pub deposit_spot_asset: String,
    /// Initial deposit in the vault's deposit asset, as a USD decimal string (e.g. `\"15000\"`).
    #[serde(rename = "initial_deposit")]
    pub initial_deposit: bigdecimal::BigDecimal,
    /// Initial share price the vault is seeded at, in USD, as a decimal string (e.g. `\"1\"` or `\"100\"`). Must lie within the protocol's permitted range.
    #[serde(rename = "initial_share_price_usd")]
    pub initial_share_price_usd: bigdecimal::BigDecimal,
    #[serde(rename = "management_fee_bps")]
    pub management_fee_bps: i32,
    #[serde(rename = "manager_id")]
    pub manager_id: i32,
    /// Maximum sequencer fee the signer authorises, in USD, as a decimal string (e.g. `\"1.5\"`).
    #[serde(rename = "max_fee_usd")]
    pub max_fee_usd: bigdecimal::BigDecimal,
    #[serde(rename = "max_slippage_bps")]
    pub max_slippage_bps: i32,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "performance_fee_bps")]
    pub performance_fee_bps: i32,
    /// 0x-prefixed hex of the 65-byte EOA signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The subaccount the action is signed on; which subaccount applies depends on the specific method — see that method's reference.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl CreateVaultRequest {
    /// Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
    pub fn new(cooldown_sec: i32, deposit_spot_asset: String, initial_deposit: bigdecimal::BigDecimal, initial_share_price_usd: bigdecimal::BigDecimal, management_fee_bps: i32, manager_id: i32, max_fee_usd: bigdecimal::BigDecimal, max_slippage_bps: i32, nonce: i32, performance_fee_bps: i32, signature: String, signature_expiry_sec: i32, signer: String, subaccount_id: i32) -> CreateVaultRequest {
        CreateVaultRequest {
            benchmark_asset: None,
            cooldown_sec,
            deposit_spot_asset,
            initial_deposit,
            initial_share_price_usd,
            management_fee_bps,
            manager_id,
            max_fee_usd,
            max_slippage_bps,
            nonce,
            performance_fee_bps,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

