/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateOrderRequest : `private/order` params.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderRequest {
    #[serde(rename = "algo_duration_sec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_duration_sec: Option<Option<i32>>,
    #[serde(rename = "algo_num_slices", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_num_slices: Option<Option<i32>>,
    #[serde(rename = "algo_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_type: Option<Option<models::AlgoType>>,
    /// Order amount in units of the base, as a decimal string (e.g. `\"1.5\"`) or a JSON number.
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "client", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client: Option<Option<String>>,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Optional extra fee per unit of volume, as a decimal string or JSON number. Defaults to zero.
    #[serde(rename = "extra_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_fee: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "is_atomic_signing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_atomic_signing: Option<Option<bool>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    /// Limit price in quote currency, as a decimal string (e.g. `\"3100.5\"`) or a JSON number.
    #[serde(rename = "limit_price")]
    pub limit_price: bigdecimal::BigDecimal,
    /// Max fee per unit of volume in quote currency, as a decimal string or a JSON number.
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "mmp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mmp: Option<Option<bool>>,
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "order_type", skip_serializing_if = "Option::is_none")]
    pub order_type: Option<models::OrderType>,
    #[serde(rename = "reduce_only", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<Option<bool>>,
    #[serde(rename = "referral_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<Option<String>>,
    #[serde(rename = "reject_post_only", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reject_post_only: Option<Option<bool>>,
    #[serde(rename = "reject_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reject_timestamp: Option<Option<i64>>,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "time_in_force", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<models::TimeInForce>,
    /// Trigger price as a decimal string or JSON number; omit for non-trigger orders.
    #[serde(rename = "trigger_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_price: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "trigger_price_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_price_type: Option<Option<models::TriggerPriceType>>,
    #[serde(rename = "trigger_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_type: Option<Option<models::TriggerType>>,
}

impl CreateOrderRequest {
    /// `private/order` params.
    pub fn new(amount: bigdecimal::BigDecimal, direction: models::Direction, instrument_name: String, limit_price: bigdecimal::BigDecimal, max_fee: bigdecimal::BigDecimal, nonce: String, signature: String, signature_expiry_sec: i64, signer: String, subaccount_id: i64) -> CreateOrderRequest {
        CreateOrderRequest {
            algo_duration_sec: None,
            algo_num_slices: None,
            algo_type: None,
            amount,
            client: None,
            direction,
            extra_fee: None,
            instrument_name,
            is_atomic_signing: None,
            label: None,
            limit_price,
            max_fee,
            mmp: None,
            nonce,
            order_type: None,
            reduce_only: None,
            referral_code: None,
            reject_post_only: None,
            reject_timestamp: None,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
            time_in_force: None,
            trigger_price: None,
            trigger_price_type: None,
            trigger_type: None,
        }
    }
}

