/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Currency : A currency's spot price and its assets grouped by type. Managers risking the currency are listed per universe under `managers`; asset-level risk — OI, lending, and discounts — lives under each asset's `universes`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Currency {
    #[serde(rename = "currency")]
    pub currency: String,
    /// Managers risk-pricing this currency, one entry per universe where at least one manager covers it.
    #[serde(rename = "managers")]
    pub managers: Vec<models::UniverseManagers>,
    /// Which instrument/collateral classes the currency is enabled for.
    #[serde(rename = "market_type")]
    pub market_type: models::MarketType,
    #[serde(rename = "option", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option: Option<Option<models::AssetEntry>>,
    #[serde(rename = "perp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub perp: Option<Option<models::AssetEntry>>,
    /// Every spot asset registered to this currency (e.g. lending \"USDC\" and non-lending \"USDC-NL\").
    #[serde(rename = "spot")]
    pub spot: Vec<models::SpotAssetEntry>,
    #[serde(rename = "spot_price")]
    pub spot_price: String,
    #[serde(rename = "spot_price_24h", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spot_price_24h: Option<Option<String>>,
}

impl Currency {
    /// A currency's spot price and its assets grouped by type. Managers risking the currency are listed per universe under `managers`; asset-level risk — OI, lending, and discounts — lives under each asset's `universes`.
    pub fn new(currency: String, managers: Vec<models::UniverseManagers>, market_type: models::MarketType, spot: Vec<models::SpotAssetEntry>, spot_price: String) -> Currency {
        Currency {
            currency,
            managers,
            market_type,
            option: None,
            perp: None,
            spot,
            spot_price,
            spot_price_24h: None,
        }
    }
}

