/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyTradingStatistics {
    /// Number of contracts traded during last 24 hours
    #[serde(rename = "c")]
    pub c: bigdecimal::BigDecimal,
    /// Highest trade price during last 24h
    #[serde(rename = "h")]
    pub h: bigdecimal::BigDecimal,
    /// Lowest trade price during last 24h
    #[serde(rename = "l")]
    pub l: bigdecimal::BigDecimal,
    /// Number of trades during last 24h
    #[serde(rename = "n")]
    pub n: i32,
    /// Current total open interest
    #[serde(rename = "oi")]
    pub oi: bigdecimal::BigDecimal,
    /// Options: 24hr percent change in premium; Perps: 24hr percent change in mark price
    #[serde(rename = "p")]
    pub p: bigdecimal::BigDecimal,
    /// Premium volume traded during last 24 hours
    #[serde(rename = "pr")]
    pub pr: bigdecimal::BigDecimal,
    /// Notional volume traded during last 24 hours
    #[serde(rename = "v")]
    pub v: bigdecimal::BigDecimal,
}

impl DailyTradingStatistics {
    pub fn new(c: bigdecimal::BigDecimal, h: bigdecimal::BigDecimal, l: bigdecimal::BigDecimal, n: i32, oi: bigdecimal::BigDecimal, p: bigdecimal::BigDecimal, pr: bigdecimal::BigDecimal, v: bigdecimal::BigDecimal) -> DailyTradingStatistics {
        DailyTradingStatistics {
            c,
            h,
            l,
            n,
            oi,
            p,
            pr,
            v,
        }
    }
}

