/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DepositEntry : `amount` and `fee` are decimal strings (e.g. `\"1.1\"`); the net credited amount is `amount - fee`. `operation_id`/`batch_uuid` are stable uuids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositEntry {
    #[serde(rename = "action_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub action_id: Option<Option<i32>>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "batch_status")]
    pub batch_status: models::BatchStatus,
    #[serde(rename = "batch_uuid")]
    pub batch_uuid: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fee")]
    pub fee: bigdecimal::BigDecimal,
    #[serde(rename = "new_subaccount")]
    pub new_subaccount: bool,
    #[serde(rename = "operation_id")]
    pub operation_id: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl DepositEntry {
    /// `amount` and `fee` are decimal strings (e.g. `\"1.1\"`); the net credited amount is `amount - fee`. `operation_id`/`batch_uuid` are stable uuids.
    pub fn new(amount: bigdecimal::BigDecimal, asset: String, batch_status: models::BatchStatus, batch_uuid: String, fee: bigdecimal::BigDecimal, new_subaccount: bool, operation_id: String, subaccount_id: i32, timestamp: i32, wallet: String) -> DepositEntry {
        DepositEntry {
            action_id: None,
            amount,
            asset,
            batch_status,
            batch_uuid,
            fee,
            new_subaccount,
            operation_id,
            subaccount_id,
            timestamp,
            tx_hash: None,
            wallet,
        }
    }
}

