/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditSessionKeyRequest {
    #[serde(rename = "ip_whitelist", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_whitelist: Option<Option<Vec<String>>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "offchain_scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offchain_scopes: Option<Option<Vec<String>>>,
    #[serde(rename = "public_session_key")]
    pub public_session_key: String,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl EditSessionKeyRequest {
    pub fn new(public_session_key: String, wallet: String) -> EditSessionKeyRequest {
        EditSessionKeyRequest {
            ip_whitelist: None,
            label: None,
            offchain_scopes: None,
            public_session_key,
            wallet,
        }
    }
}

