/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Erc20Details {
    #[serde(rename = "decimals")]
    pub decimals: i32,
    /// On-chain ERC20 token deposited into the spot asset (informational).
    #[serde(rename = "underlying_erc20", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub underlying_erc20: Option<Option<String>>,
}

impl Erc20Details {
    pub fn new(decimals: i32) -> Erc20Details {
        Erc20Details {
            decimals,
            underlying_erc20: None,
        }
    }
}

