/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteQuoteRequest {
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    #[serde(rename = "direction", deserialize_with = "Option::deserialize")]
    pub direction: Option<serde_json::Value>,
    #[serde(rename = "enable_taker_protection", skip_serializing_if = "Option::is_none")]
    pub enable_taker_protection: Option<bool>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "legs", deserialize_with = "Option::deserialize")]
    pub legs: Option<serde_json::Value>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "nonce", deserialize_with = "Option::deserialize")]
    pub nonce: Option<serde_json::Value>,
    /// UUID v4 string
    #[serde(rename = "quote_id")]
    pub quote_id: uuid::Uuid,
    #[serde(rename = "referral_code", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<String>,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "signature", deserialize_with = "Option::deserialize")]
    pub signature: Option<serde_json::Value>,
    #[serde(rename = "signature_expiry_sec", deserialize_with = "Option::deserialize")]
    pub signature_expiry_sec: Option<serde_json::Value>,
    #[serde(rename = "signer", deserialize_with = "Option::deserialize")]
    pub signer: Option<serde_json::Value>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl ExecuteQuoteRequest {
    pub fn new(direction: Option<serde_json::Value>, legs: Option<serde_json::Value>, max_fee: bigdecimal::BigDecimal, nonce: Option<serde_json::Value>, quote_id: uuid::Uuid, rfq_id: uuid::Uuid, signature: Option<serde_json::Value>, signature_expiry_sec: Option<serde_json::Value>, signer: Option<serde_json::Value>, subaccount_id: i32) -> ExecuteQuoteRequest {
        ExecuteQuoteRequest {
            client: None,
            direction,
            enable_taker_protection: None,
            label: None,
            legs,
            max_fee,
            nonce,
            quote_id,
            referral_code: None,
            rfq_id,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

