/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExpirySettlementPrice : One settled expiry and its settlement price.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpirySettlementPrice {
    /// Expiry date in `YYYYMMDD` format.
    #[serde(rename = "expiry_date")]
    pub expiry_date: String,
    /// Settlement price. Only settled expiries are returned, so never null.
    #[serde(rename = "price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price: Option<Option<String>>,
    /// UTC timestamp of expiry, unix seconds.
    #[serde(rename = "utc_expiry_sec")]
    pub utc_expiry_sec: i32,
}

impl ExpirySettlementPrice {
    /// One settled expiry and its settlement price.
    pub fn new(expiry_date: String, utc_expiry_sec: i32) -> ExpirySettlementPrice {
        ExpirySettlementPrice {
            expiry_date,
            price: None,
            utc_expiry_sec,
        }
    }
}

