/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForceBurnRequest {
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "holder")]
    pub holder: String,
    /// The vault's subaccount ID.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl ForceBurnRequest {
    pub fn new(holder: String, subaccount_id: i32) -> ForceBurnRequest {
        ForceBurnRequest {
            holder,
            subaccount_id,
        }
    }
}

