/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForwardFeedDataResponse {
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deadline")]
    pub deadline: i32,
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "fwd_diff")]
    pub fwd_diff: String,
    #[serde(rename = "signatures")]
    pub signatures: models::OracleSignatureDataResponse,
    #[serde(rename = "spot_aggregate_latest")]
    pub spot_aggregate_latest: String,
    #[serde(rename = "spot_aggregate_start")]
    pub spot_aggregate_start: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl ForwardFeedDataResponse {
    pub fn new(confidence: String, currency: String, deadline: i32, expiry: i32, fwd_diff: String, signatures: models::OracleSignatureDataResponse, spot_aggregate_latest: String, spot_aggregate_start: String, timestamp: i32) -> ForwardFeedDataResponse {
        ForwardFeedDataResponse {
            confidence,
            currency,
            deadline,
            expiry,
            fwd_diff,
            signatures,
            spot_aggregate_latest,
            spot_aggregate_start,
            timestamp,
        }
    }
}

