/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FundingRateCandle : Single funding-rate OHLC candle. `funding_rate` mirrors `close` for backward compatibility with the pre-OHLC response shape; `timestamp` is the bucket start in UTC milliseconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FundingRateCandle {
    #[serde(rename = "close")]
    pub close: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "funding_rate")]
    pub funding_rate: String,
    #[serde(rename = "high")]
    pub high: String,
    #[serde(rename = "low")]
    pub low: String,
    #[serde(rename = "open")]
    pub open: String,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl FundingRateCandle {
    /// Single funding-rate OHLC candle. `funding_rate` mirrors `close` for backward compatibility with the pre-OHLC response shape; `timestamp` is the bucket start in UTC milliseconds.
    pub fn new(close: String, currency: String, funding_rate: String, high: String, low: String, open: String, risk_universe_id: i32, timestamp: i64) -> FundingRateCandle {
        FundingRateCandle {
            close,
            currency,
            funding_rate,
            high,
            low,
            open,
            risk_universe_id,
            timestamp,
        }
    }
}

