/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestSignedFeedsRequest {
    /// Currency filter, (defaults to all currencies)
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    /// Expiry filter for options and forward data (defaults to all expiries). Use `0` to get data only for spot and perpetuals.
    #[serde(rename = "expiry", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<Option<i32>>,
}

impl GetLatestSignedFeedsRequest {
    pub fn new() -> GetLatestSignedFeedsRequest {
        GetLatestSignedFeedsRequest {
            currency: None,
            expiry: None,
        }
    }
}

