/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPendingDepositsParams {
    /// Wallet the pending deposits credit.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl GetPendingDepositsParams {
    pub fn new(wallet: String) -> GetPendingDepositsParams {
        GetPendingDepositsParams {
            wallet,
        }
    }
}

