/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetOptionSettlementPricesRequest : Parameters for `public/get_option_settlement_prices`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOptionSettlementPricesRequest {
    #[serde(rename = "currency")]
    pub currency: String,
}

impl GetOptionSettlementPricesRequest {
    /// Parameters for `public/get_option_settlement_prices`.
    pub fn new(currency: String) -> GetOptionSettlementPricesRequest {
        GetOptionSettlementPricesRequest {
            currency,
        }
    }
}

