/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetReferralPerformanceParams {
    /// End timestamp in UTC milliseconds.
    #[serde(rename = "end_ms")]
    pub end_ms: i64,
    /// (Optional) referral code.
    #[serde(rename = "referral_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<Option<String>>,
    /// Start timestamp in UTC milliseconds.
    #[serde(rename = "start_ms")]
    pub start_ms: i64,
    /// (Optional) wallet of the referrer.
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetReferralPerformanceParams {
    pub fn new(end_ms: i64, start_ms: i64) -> GetReferralPerformanceParams {
        GetReferralPerformanceParams {
            end_ms,
            referral_code: None,
            start_ms,
            wallet: None,
        }
    }
}

