/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFundingHistoryRequest : Parameters for `private/get_funding_history`.  `subaccount_id`, `start_timestamp`, and `end_timestamp` accept either a JSON number or a string-encoded integer. Pagination is `page` >= 1, `page_size` in 1..=1000.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFundingHistoryRequest {
    #[serde(rename = "end_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<Option<i64>>,
    #[serde(rename = "instrument_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<Option<String>>,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "start_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<Option<i64>>,
    #[serde(rename = "subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<Option<i32>>,
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetFundingHistoryRequest {
    /// Parameters for `private/get_funding_history`.  `subaccount_id`, `start_timestamp`, and `end_timestamp` accept either a JSON number or a string-encoded integer. Pagination is `page` >= 1, `page_size` in 1..=1000.
    pub fn new() -> GetFundingHistoryRequest {
        GetFundingHistoryRequest {
            end_timestamp: None,
            instrument_name: None,
            page: None,
            page_size: None,
            start_timestamp: None,
            subaccount_id: None,
            wallet: None,
        }
    }
}

