/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVaultRequestHistoryRequest {
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    /// The shareholder wallet (0x hex).
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl GetVaultRequestHistoryRequest {
    pub fn new(wallet: String) -> GetVaultRequestHistoryRequest {
        GetVaultRequestHistoryRequest {
            page: None,
            page_size: None,
            wallet,
        }
    }
}

