/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletsFromSessionKeyRequest {
    #[serde(rename = "public_session_key")]
    pub public_session_key: String,
    #[serde(rename = "scope", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Option<models::OffchainKeyScope>>,
}

impl GetWalletsFromSessionKeyRequest {
    pub fn new(public_session_key: String) -> GetWalletsFromSessionKeyRequest {
        GetWalletsFromSessionKeyRequest {
            public_session_key,
            scope: None,
        }
    }
}

