/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOnchainActionHistoryParams {
    /// On-chain `actionType` id.
    #[serde(rename = "action_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub action_type: Option<Option<i32>>,
    #[serde(rename = "end_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<Option<i64>>,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "start_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<Option<i64>>,
    /// L1 sender of the action (any hex casing).
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetOnchainActionHistoryParams {
    pub fn new() -> GetOnchainActionHistoryParams {
        GetOnchainActionHistoryParams {
            action_type: None,
            end_timestamp: None,
            page: None,
            page_size: None,
            start_timestamp: None,
            wallet: None,
        }
    }
}

