/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInterestHistoryRequest : Parameters for `private/get_interest_history`. `wallet`, when set, takes precedence over `subaccount_id` and returns the whole wallet's settlements. `[start_timestamp, end_timestamp]` is a unix-millisecond window. Results are capped at 1000 rows, newest first.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInterestHistoryRequest {
    /// End of the window, unix milliseconds (default: now / unbounded).
    #[serde(rename = "end_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<Option<i32>>,
    /// Start of the window, unix milliseconds (default 0).
    #[serde(rename = "start_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<Option<i32>>,
    #[serde(rename = "subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<Option<i32>>,
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetInterestHistoryRequest {
    /// Parameters for `private/get_interest_history`. `wallet`, when set, takes precedence over `subaccount_id` and returns the whole wallet's settlements. `[start_timestamp, end_timestamp]` is a unix-millisecond window. Results are capped at 1000 rows, newest first.
    pub fn new() -> GetInterestHistoryRequest {
        GetInterestHistoryRequest {
            end_timestamp: None,
            start_timestamp: None,
            subaccount_id: None,
            wallet: None,
        }
    }
}

