/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetOptionSettlementHistoryParams : Parameters for `private/get_option_settlement_history`. One of `wallet` or `subaccount_id` must be provided; `wallet` returns every subaccount's settlements.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOptionSettlementHistoryParams {
    #[serde(rename = "subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<Option<i32>>,
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetOptionSettlementHistoryParams {
    /// Parameters for `private/get_option_settlement_history`. One of `wallet` or `subaccount_id` must be provided; `wallet` returns every subaccount's settlements.
    pub fn new() -> GetOptionSettlementHistoryParams {
        GetOptionSettlementHistoryParams {
            subaccount_id: None,
            wallet: None,
        }
    }
}

