/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllInstrumentsResponse {
    #[serde(rename = "instruments")]
    pub instruments: Vec<models::Instrument>,
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
}

impl GetAllInstrumentsResponse {
    pub fn new(instruments: Vec<models::Instrument>, pagination: models::Pagination) -> GetAllInstrumentsResponse {
        GetAllInstrumentsResponse {
            instruments,
            pagination,
        }
    }
}

