/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTickersRequest : Parameters for `public/get_tickers`. `expiry_date` accepts either a JSON number or a string-encoded 8-digit date (e.g. `20260511`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTickersRequest {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    #[serde(rename = "expiry_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<Option<serde_json::Value>>,
    #[serde(rename = "instrument_type")]
    pub instrument_type: models::AssetType,
}

impl GetTickersRequest {
    /// Parameters for `public/get_tickers`. `expiry_date` accepts either a JSON number or a string-encoded 8-digit date (e.g. `20260511`).
    pub fn new(instrument_type: models::AssetType) -> GetTickersRequest {
        GetTickersRequest {
            currency: None,
            expiry_date: None,
            instrument_type,
        }
    }
}

