/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVaultPerformanceHistoryRequest {
    /// Optional inclusive lower bound (unix seconds).
    #[serde(rename = "from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from: Option<Option<i64>>,
    /// Max points to return, newest first (default 1000, capped at 10000).
    #[serde(rename = "limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Option<i32>>,
    #[serde(rename = "resolution")]
    pub resolution: models::PerformanceResolution,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// Optional exclusive upper bound (unix seconds).
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<i64>>,
}

impl GetVaultPerformanceHistoryRequest {
    pub fn new(resolution: models::PerformanceResolution, subaccount_id: i32) -> GetVaultPerformanceHistoryRequest {
        GetVaultPerformanceHistoryRequest {
            from: None,
            limit: None,
            resolution,
            subaccount_id,
            to: None,
        }
    }
}

