/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLiveVaultRequestsRequest {
    /// The shareholder wallet (0x hex).
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl GetLiveVaultRequestsRequest {
    pub fn new(wallet: String) -> GetLiveVaultRequestsRequest {
        GetLiveVaultRequestsRequest {
            wallet,
        }
    }
}

