/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPublicTradeHistoryRequest {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    #[serde(rename = "from_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_timestamp: Option<Option<i64>>,
    #[serde(rename = "instrument_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<Option<String>>,
    #[serde(rename = "instrument_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instrument_type: Option<Option<String>>,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<Option<i64>>,
    #[serde(rename = "to_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to_timestamp: Option<Option<i64>>,
    #[serde(rename = "trade_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trade_id: Option<Option<String>>,
    #[serde(rename = "tx_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_status: Option<Option<String>>,
}

impl GetPublicTradeHistoryRequest {
    pub fn new() -> GetPublicTradeHistoryRequest {
        GetPublicTradeHistoryRequest {
            currency: None,
            from_timestamp: None,
            instrument_name: None,
            instrument_type: None,
            page: None,
            page_size: None,
            subaccount_id: None,
            to_timestamp: None,
            trade_id: None,
            tx_status: None,
        }
    }
}

