/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCuratedVaultsRequest {
    /// The curator wallet (0x hex).
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl GetCuratedVaultsRequest {
    pub fn new(wallet: String) -> GetCuratedVaultsRequest {
        GetCuratedVaultsRequest {
            wallet,
        }
    }
}

