/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTradeHistoryRequest {
    #[serde(rename = "from_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_timestamp: Option<Option<i64>>,
    #[serde(rename = "instrument_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<Option<String>>,
    #[serde(rename = "order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Option<String>>,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "quote_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<Option<String>>,
    #[serde(rename = "subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<Option<i64>>,
    #[serde(rename = "to_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to_timestamp: Option<Option<i64>>,
    #[serde(rename = "wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Option<String>>,
}

impl GetTradeHistoryRequest {
    pub fn new() -> GetTradeHistoryRequest {
        GetTradeHistoryRequest {
            from_timestamp: None,
            instrument_name: None,
            order_id: None,
            page: None,
            page_size: None,
            quote_id: None,
            subaccount_id: None,
            to_timestamp: None,
            wallet: None,
        }
    }
}

