/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestSignedFeedsResponse {
    /// currency -> expiry -> latest forward feed data
    #[serde(rename = "fwd_data")]
    pub fwd_data: std::collections::HashMap<String, std::collections::HashMap<String, models::ForwardFeedDataResponse>>,
    /// currency -> feed type -> latest perp feed data
    #[serde(rename = "perp_data")]
    pub perp_data: std::collections::HashMap<String, std::collections::HashMap<String, models::PerpFeedDataResponse>>,
    /// currency -> expiry -> latest rate feed data
    #[serde(rename = "rate_data")]
    pub rate_data: std::collections::HashMap<String, std::collections::HashMap<String, models::RateFeedDataResponse>>,
    /// currency -> latest spot feed data
    #[serde(rename = "spot_data")]
    pub spot_data: std::collections::HashMap<String, models::SpotFeedDataResponse>,
    /// currency -> expiry -> latest vol feed data
    #[serde(rename = "vol_data")]
    pub vol_data: std::collections::HashMap<String, std::collections::HashMap<String, models::VolFeedDataResponse>>,
}

impl GetLatestSignedFeedsResponse {
    pub fn new(fwd_data: std::collections::HashMap<String, std::collections::HashMap<String, models::ForwardFeedDataResponse>>, perp_data: std::collections::HashMap<String, std::collections::HashMap<String, models::PerpFeedDataResponse>>, rate_data: std::collections::HashMap<String, std::collections::HashMap<String, models::RateFeedDataResponse>>, spot_data: std::collections::HashMap<String, models::SpotFeedDataResponse>, vol_data: std::collections::HashMap<String, std::collections::HashMap<String, models::VolFeedDataResponse>>) -> GetLatestSignedFeedsResponse {
        GetLatestSignedFeedsResponse {
            fwd_data,
            perp_data,
            rate_data,
            spot_data,
            vol_data,
        }
    }
}

