/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInterestRateHistoryRequest : Parameters for `public/get_interest_rate_history`. Timestamp fields accept either a JSON number or a string-encoded integer, and are UTC milliseconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInterestRateHistoryRequest {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "end_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<Option<i64>>,
    #[serde(rename = "period", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub period: Option<Option<i64>>,
    /// Restrict to one risk universe's pool. Omit to return every universe's candles for the currency (each candle is tagged with its universe).
    #[serde(rename = "risk_universe_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_universe_id: Option<Option<i32>>,
    #[serde(rename = "start_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<Option<i64>>,
}

impl GetInterestRateHistoryRequest {
    /// Parameters for `public/get_interest_rate_history`. Timestamp fields accept either a JSON number or a string-encoded integer, and are UTC milliseconds.
    pub fn new(currency: String) -> GetInterestRateHistoryRequest {
        GetInterestRateHistoryRequest {
            currency,
            end_timestamp: None,
            period: None,
            risk_universe_id: None,
            start_timestamp: None,
        }
    }
}

