/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllInstrumentsRequest {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    #[serde(rename = "expired")]
    pub expired: bool,
    #[serde(rename = "instrument_type")]
    pub instrument_type: models::AssetType,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "risk_universe_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_universe_id: Option<Option<i32>>,
}

impl GetAllInstrumentsRequest {
    pub fn new(expired: bool, instrument_type: models::AssetType) -> GetAllInstrumentsRequest {
        GetAllInstrumentsRequest {
            currency: None,
            expired,
            instrument_type,
            page: None,
            page_size: None,
            risk_universe_id: None,
        }
    }
}

