/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLiveMintRequestsRequest {
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl GetLiveMintRequestsRequest {
    pub fn new(limit: i32, subaccount_id: i32) -> GetLiveMintRequestsRequest {
        GetLiveMintRequestsRequest {
            limit,
            subaccount_id,
        }
    }
}

