/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTradingviewChartDataRequest : Parameters for `public/get_tradingview_chart_data`. Numeric fields accept either a JSON number or a string-encoded integer. Timestamps are UTC seconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTradingviewChartDataRequest {
    #[serde(rename = "end_timestamp")]
    pub end_timestamp: i32,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "period")]
    pub period: i32,
    #[serde(rename = "start_timestamp")]
    pub start_timestamp: i32,
}

impl GetTradingviewChartDataRequest {
    /// Parameters for `public/get_tradingview_chart_data`. Numeric fields accept either a JSON number or a string-encoded integer. Timestamps are UTC seconds.
    pub fn new(end_timestamp: i32, instrument_name: String, period: i32, start_timestamp: i32) -> GetTradingviewChartDataRequest {
        GetTradingviewChartDataRequest {
            end_timestamp,
            instrument_name,
            period,
            start_timestamp,
        }
    }
}

