/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFundingRateHistoryRequest : Parameters for `public/get_funding_rate_history`. Timestamp fields accept either a JSON number or a string-encoded integer, and are UTC milliseconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFundingRateHistoryRequest {
    #[serde(rename = "end_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<Option<i64>>,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "period", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub period: Option<Option<i64>>,
    #[serde(rename = "start_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<Option<i64>>,
}

impl GetFundingRateHistoryRequest {
    /// Parameters for `public/get_funding_rate_history`. Timestamp fields accept either a JSON number or a string-encoded integer, and are UTC milliseconds.
    pub fn new(instrument_name: String) -> GetFundingRateHistoryRequest {
        GetFundingRateHistoryRequest {
            end_timestamp: None,
            instrument_name,
            period: None,
            start_timestamp: None,
        }
    }
}

