/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTickerRequest {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
}

impl GetTickerRequest {
    pub fn new(instrument_name: String) -> GetTickerRequest {
        GetTickerRequest {
            instrument_name,
        }
    }
}

