/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountRequest {
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl GetAccountRequest {
    pub fn new(wallet: String) -> GetAccountRequest {
        GetAccountRequest {
            wallet,
        }
    }
}

