/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetIndexChartDataRequest : Parameters for `public/get_index_chart_data`. Numeric fields accept either a JSON number or a string-encoded integer. Timestamps are UTC seconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIndexChartDataRequest {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "end_timestamp")]
    pub end_timestamp: i32,
    #[serde(rename = "period")]
    pub period: i32,
    #[serde(rename = "start_timestamp")]
    pub start_timestamp: i32,
}

impl GetIndexChartDataRequest {
    /// Parameters for `public/get_index_chart_data`. Numeric fields accept either a JSON number or a string-encoded integer. Timestamps are UTC seconds.
    pub fn new(currency: String, end_timestamp: i32, period: i32, start_timestamp: i32) -> GetIndexChartDataRequest {
        GetIndexChartDataRequest {
            currency,
            end_timestamp,
            period,
            start_timestamp,
        }
    }
}

