/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssetsRequest {
    #[serde(rename = "asset_type")]
    pub asset_type: models::AssetType,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "expired")]
    pub expired: bool,
}

impl GetAssetsRequest {
    pub fn new(asset_type: models::AssetType, currency: String, expired: bool) -> GetAssetsRequest {
        GetAssetsRequest {
            asset_type,
            currency,
            expired,
        }
    }
}

