/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTickersResponse : A map of instrument name to ticker: `{\"tickers\": {<instrument_name>: <ticker_data>}}`. Each ticker value matches the payload of a `ticker_slim.{instrument_name}.{interval}` subscription update.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTickersResponse {
    #[serde(rename = "tickers")]
    pub tickers: std::collections::HashMap<String, serde_json::Value>,
}

impl GetTickersResponse {
    /// A map of instrument name to ticker: `{\"tickers\": {<instrument_name>: <ticker_data>}}`. Each ticker value matches the payload of a `ticker_slim.{instrument_name}.{interval}` subscription update.
    pub fn new(tickers: std::collections::HashMap<String, serde_json::Value>) -> GetTickersResponse {
        GetTickersResponse {
            tickers,
        }
    }
}

