/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOnchainActionHistoryResponse {
    #[serde(rename = "actions")]
    pub actions: Vec<models::OnchainActionHistoryEntry>,
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
}

impl GetOnchainActionHistoryResponse {
    pub fn new(actions: Vec<models::OnchainActionHistoryEntry>, pagination: models::Pagination) -> GetOnchainActionHistoryResponse {
        GetOnchainActionHistoryResponse {
            actions,
            pagination,
        }
    }
}

