/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVaultActionHistoryRequest {
    /// Optional: \"vault_deposit\" | \"vault_withdraw\" | \"vault_fee_accrual\".
    #[serde(rename = "event_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<Option<String>>,
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    #[serde(rename = "page_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl GetVaultActionHistoryRequest {
    pub fn new(subaccount_id: i32) -> GetVaultActionHistoryRequest {
        GetVaultActionHistoryRequest {
            event_type: None,
            page: None,
            page_size: None,
            subaccount_id,
        }
    }
}

