/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexCandle : Single spot OHLC candle in `public/get_index_chart_data`. `price` mirrors the close; `timestamp` and `timestamp_bucket` are the bucket start in UTC seconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexCandle {
    #[serde(rename = "close_price")]
    pub close_price: String,
    #[serde(rename = "high_price")]
    pub high_price: String,
    #[serde(rename = "low_price")]
    pub low_price: String,
    #[serde(rename = "open_price")]
    pub open_price: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "timestamp_bucket")]
    pub timestamp_bucket: i64,
}

impl IndexCandle {
    /// Single spot OHLC candle in `public/get_index_chart_data`. `price` mirrors the close; `timestamp` and `timestamp_bucket` are the bucket start in UTC seconds.
    pub fn new(close_price: String, high_price: String, low_price: String, open_price: String, price: String, timestamp: i64, timestamp_bucket: i64) -> IndexCandle {
        IndexCandle {
            close_price,
            high_price,
            low_price,
            open_price,
            price,
            timestamp,
            timestamp_bucket,
        }
    }
}

