/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instrument {
    #[serde(rename = "amount_step")]
    pub amount_step: String,
    /// The traded asset's contract address — word 0 (`asset`) of the order action `data`. Use this (not `erc20_details`) when signing an order.
    #[serde(rename = "base_asset_address")]
    pub base_asset_address: String,
    /// The traded asset's sub-id — word 1 (`subId`) of the order action `data`. Decimal string; `\"0\"` for perps and spot.
    #[serde(rename = "base_asset_sub_id")]
    pub base_asset_sub_id: String,
    #[serde(rename = "base_currency")]
    pub base_currency: String,
    #[serde(rename = "base_fee")]
    pub base_fee: String,
    #[serde(rename = "erc20_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub erc20_details: Option<Option<models::Erc20Details>>,
    #[serde(rename = "fifo_min_allocation")]
    pub fifo_min_allocation: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "instrument_type")]
    pub instrument_type: models::AssetType,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "maker_fee_rate")]
    pub maker_fee_rate: String,
    #[serde(rename = "mark_price_fee_rate_cap", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mark_price_fee_rate_cap: Option<Option<String>>,
    #[serde(rename = "maximum_amount")]
    pub maximum_amount: String,
    #[serde(rename = "minimum_amount")]
    pub minimum_amount: String,
    #[serde(rename = "option_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_details: Option<Option<models::OptionDetails>>,
    #[serde(rename = "perp_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub perp_details: Option<Option<models::PerpDetails>>,
    #[serde(rename = "pro_rata_amount_step")]
    pub pro_rata_amount_step: String,
    #[serde(rename = "pro_rata_fraction")]
    pub pro_rata_fraction: String,
    #[serde(rename = "quote_currency")]
    pub quote_currency: String,
    #[serde(rename = "scheduled_activation")]
    pub scheduled_activation: i64,
    #[serde(rename = "scheduled_deactivation")]
    pub scheduled_deactivation: i64,
    #[serde(rename = "taker_fee_rate")]
    pub taker_fee_rate: String,
    #[serde(rename = "tick_size")]
    pub tick_size: String,
}

impl Instrument {
    pub fn new(amount_step: String, base_asset_address: String, base_asset_sub_id: String, base_currency: String, base_fee: String, fifo_min_allocation: String, instrument_name: String, instrument_type: models::AssetType, is_active: bool, maker_fee_rate: String, maximum_amount: String, minimum_amount: String, pro_rata_amount_step: String, pro_rata_fraction: String, quote_currency: String, scheduled_activation: i64, scheduled_deactivation: i64, taker_fee_rate: String, tick_size: String) -> Instrument {
        Instrument {
            amount_step,
            base_asset_address,
            base_asset_sub_id,
            base_currency,
            base_fee,
            erc20_details: None,
            fifo_min_allocation,
            instrument_name,
            instrument_type,
            is_active,
            maker_fee_rate,
            mark_price_fee_rate_cap: None,
            maximum_amount,
            minimum_amount,
            option_details: None,
            perp_details: None,
            pro_rata_amount_step,
            pro_rata_fraction,
            quote_currency,
            scheduled_activation,
            scheduled_deactivation,
            taker_fee_rate,
            tick_size,
        }
    }
}

