/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterestPayment : One realized interest settlement. `interest` is a decimal string; negative = paid, positive = received. `timestamp` is unix ms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterestPayment {
    #[serde(rename = "interest")]
    pub interest: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl InterestPayment {
    /// One realized interest settlement. `interest` is a decimal string; negative = paid, positive = received. `timestamp` is unix ms.
    pub fn new(interest: String, subaccount_id: i32, timestamp: i64) -> InterestPayment {
        InterestPayment {
            interest,
            subaccount_id,
            timestamp,
        }
    }
}

