/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterestRateCandle : One interest-rate candle: OHLC of the annualized borrow and supply APY plus the pool totals at the bucket close. `timestamp` is the bucket start in UTC milliseconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterestRateCandle {
    #[serde(rename = "borrow_apy")]
    pub borrow_apy: models::Ohlc,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    #[serde(rename = "supply_apy")]
    pub supply_apy: models::Ohlc,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "total_borrow")]
    pub total_borrow: String,
    #[serde(rename = "total_supply")]
    pub total_supply: String,
}

impl InterestRateCandle {
    /// One interest-rate candle: OHLC of the annualized borrow and supply APY plus the pool totals at the bucket close. `timestamp` is the bucket start in UTC milliseconds.
    pub fn new(borrow_apy: models::Ohlc, risk_universe_id: i32, supply_apy: models::Ohlc, timestamp: i64, total_borrow: String, total_supply: String) -> InterestRateCandle {
        InterestRateCandle {
            borrow_apy,
            risk_universe_id,
            supply_apy,
            timestamp,
            total_borrow,
            total_supply,
        }
    }
}

