/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegUnpricedParams {
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
}

impl LegUnpricedParams {
    pub fn new(amount: bigdecimal::BigDecimal, direction: models::Direction, instrument_name: String) -> LegUnpricedParams {
        LegUnpricedParams {
            amount,
            direction,
            instrument_name,
        }
    }
}

