/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LendingDetails : Lending pool stats for a `(spot_asset, universe)` pair. The pool's total supply is reported in the `current_open_interest` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LendingDetails {
    #[serde(rename = "borrow_apy")]
    pub borrow_apy: String,
    #[serde(rename = "supply_apy")]
    pub supply_apy: String,
    #[serde(rename = "total_borrow")]
    pub total_borrow: String,
    /// Borrow ceiling for this lending asset in this universe.
    #[serde(rename = "total_borrow_cap")]
    pub total_borrow_cap: String,
}

impl LendingDetails {
    /// Lending pool stats for a `(spot_asset, universe)` pair. The pool's total supply is reported in the `current_open_interest` field.
    pub fn new(borrow_apy: String, supply_apy: String, total_borrow: String, total_borrow_cap: String) -> LendingDetails {
        LendingDetails {
            borrow_apy,
            supply_apy,
            total_borrow,
            total_borrow_cap,
        }
    }
}

