/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ManagerCollateral : A spot asset the manager accepts as collateral, with deposit metadata and the manager's margin discounts for it (\"1\" = full credit, cash).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagerCollateral {
    /// EIP-55 checksummed protocol asset address — the `asset` argument when depositing.
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "erc20")]
    pub erc20: models::Erc20Details,
    /// Initial-margin credit for the asset under this manager.
    #[serde(rename = "im_discount")]
    pub im_discount: String,
    #[serde(rename = "min_deposit_usd")]
    pub min_deposit_usd: String,
    /// Maintenance-margin credit for the asset under this manager.
    #[serde(rename = "mm_discount")]
    pub mm_discount: String,
    /// Registered asset name (e.g. \"USDC\").
    #[serde(rename = "name")]
    pub name: String,
}

impl ManagerCollateral {
    /// A spot asset the manager accepts as collateral, with deposit metadata and the manager's margin discounts for it (\"1\" = full credit, cash).
    pub fn new(address: String, erc20: models::Erc20Details, im_discount: String, min_deposit_usd: String, mm_discount: String, name: String) -> ManagerCollateral {
        ManagerCollateral {
            address,
            erc20,
            im_discount,
            min_deposit_usd,
            mm_discount,
            name,
        }
    }
}

