/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarginType : Margin model applied by a manager: `SM` (standard, cross-collateral) or `PM2` (portfolio, scenario-based netting).
/// Margin model applied by a manager: `SM` (standard, cross-collateral) or `PM2` (portfolio, scenario-based netting).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarginType {
    #[serde(rename = "SM")]
    Sm,
    #[serde(rename = "PM2")]
    Pm2,

}

impl std::fmt::Display for MarginType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sm => write!(f, "SM"),
            Self::Pm2 => write!(f, "PM2"),
        }
    }
}

impl Default for MarginType {
    fn default() -> MarginType {
        Self::Sm
    }
}

