/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarketType {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "SRM_BASE_ONLY")]
    SrmBaseOnly,
    #[serde(rename = "SRM_OPTION_ONLY")]
    SrmOptionOnly,
    #[serde(rename = "SRM_PERP_ONLY")]
    SrmPerpOnly,
    #[serde(rename = "CASH")]
    Cash,

}

impl std::fmt::Display for MarketType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "ALL"),
            Self::SrmBaseOnly => write!(f, "SRM_BASE_ONLY"),
            Self::SrmOptionOnly => write!(f, "SRM_OPTION_ONLY"),
            Self::SrmPerpOnly => write!(f, "SRM_PERP_ONLY"),
            Self::Cash => write!(f, "CASH"),
        }
    }
}

impl Default for MarketType {
    fn default() -> MarketType {
        Self::All
    }
}

