/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MintSharesRequest : Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MintSharesRequest {
    /// 0x-prefixed hex of the 32-byte user deposit-action hash.
    #[serde(rename = "deposit_hash")]
    pub deposit_hash: String,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "request_id")]
    pub request_id: models::VaultRequestId,
    /// Quoted share price in USD per share, as a decimal string (e.g. `\"1.02\"`).
    #[serde(rename = "share_price")]
    pub share_price: bigdecimal::BigDecimal,
    /// 0x-prefixed hex of the 65-byte EOA signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The subaccount the action is signed on; which subaccount applies depends on the specific method — see that method's reference.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl MintSharesRequest {
    /// Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
    pub fn new(deposit_hash: String, nonce: i32, request_id: models::VaultRequestId, share_price: bigdecimal::BigDecimal, signature: String, signature_expiry_sec: i32, signer: String, subaccount_id: i32) -> MintSharesRequest {
        MintSharesRequest {
            deposit_hash,
            nonce,
            request_id,
            share_price,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

