/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MmpScopeRequest {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl MmpScopeRequest {
    pub fn new(subaccount_id: i32) -> MmpScopeRequest {
        MmpScopeRequest {
            currency: None,
            subaccount_id,
        }
    }
}

