/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultipleVaultRequestsResponse : Returned by `get_live_mint_requests` / `get_live_burn_requests`: a FIFO page plus the queue's total live length (so the caller can paginate).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultipleVaultRequestsResponse {
    #[serde(rename = "requests")]
    pub requests: Vec<models::VaultRequestResponse>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl MultipleVaultRequestsResponse {
    /// Returned by `get_live_mint_requests` / `get_live_burn_requests`: a FIFO page plus the queue's total live length (so the caller can paginate).
    pub fn new(requests: Vec<models::VaultRequestResponse>, total: i32) -> MultipleVaultRequestsResponse {
        MultipleVaultRequestsResponse {
            requests,
            total,
        }
    }
}

