/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OffchainAckResponse : A generic `{ \"status\": \"ok\" }` acknowledgement returned by fire-and-forget operations that have no data to return (e.g. updating account settings, MMP config, or the active currency).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffchainAckResponse {
    #[serde(rename = "status")]
    pub status: String,
}

impl OffchainAckResponse {
    /// A generic `{ \"status\": \"ok\" }` acknowledgement returned by fire-and-forget operations that have no data to return (e.g. updating account settings, MMP config, or the active currency).
    pub fn new(status: String) -> OffchainAckResponse {
        OffchainAckResponse {
            status,
        }
    }
}

