/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OffchainKeyScope : Additional permission scopes enforced off-chain (not part of the on-chain session-key scopes).
/// Additional permission scopes enforced off-chain (not part of the on-chain session-key scopes).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OffchainKeyScope {
    String(String),
    /// Permission to delete a session key. This is an off-chain-only permission, not part of the on-chain protocol scopes.
    String(String),
}

impl Default for OffchainKeyScope {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

