/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Ohlc : Open, high, low, and close for one series, each a decimal string.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ohlc {
    #[serde(rename = "close")]
    pub close: String,
    #[serde(rename = "high")]
    pub high: String,
    #[serde(rename = "low")]
    pub low: String,
    #[serde(rename = "open")]
    pub open: String,
}

impl Ohlc {
    /// Open, high, low, and close for one series, each a decimal string.
    pub fn new(close: String, high: String, low: String, open: String) -> Ohlc {
        Ohlc {
            close,
            high,
            low,
            open,
        }
    }
}

