/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnchainActionHistoryEntry {
    /// Rolling accumulator from the ActionQueued event, 0x-hex.
    #[serde(rename = "acc")]
    pub acc: String,
    #[serde(rename = "action_id")]
    pub action_id: i32,
    #[serde(rename = "action_type")]
    pub action_type: i32,
    #[serde(rename = "action_type_label")]
    pub action_type_label: String,
    #[serde(rename = "block_number")]
    pub block_number: i32,
    /// Raw action calldata, 0x-hex.
    #[serde(rename = "data")]
    pub data: String,
    /// Most recent submit rejection; null if the action never failed. Kept on applied/fallback rows as the reason the action struggled. The verbose error text stays internal (ClickHouse only).
    #[serde(rename = "error_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<i64>>,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    /// Unix ms the action was escalated with `fallback=true`; null if never escalated.
    #[serde(rename = "fallback_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fallback_at: Option<Option<i64>>,
    /// Unix ms of the first failed submit; null if the action never failed.
    #[serde(rename = "first_failed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_failed_at: Option<Option<i64>>,
    #[serde(rename = "l1_sender")]
    pub l1_sender: String,
    /// Unix ms of the most recent failed submit; null if never failed.
    #[serde(rename = "last_failed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_failed_at: Option<Option<i64>>,
    /// Operation uuid assigned by the sequencer; null until applied.
    #[serde(rename = "op_uuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub op_uuid: Option<Option<String>>,
    /// Onchain queue: 'public' or 'admin'.
    #[serde(rename = "queue")]
    pub queue: String,
    /// Sequencer applied states: 'applied' | 'applied_with_fallback' Failed States: 'instant_fallback' | 'retry_then_fallback' | 'never_escalate'
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
    /// Unix ms of the latest state change.
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl OnchainActionHistoryEntry {
    pub fn new(acc: String, action_id: i32, action_type: i32, action_type_label: String, block_number: i32, data: String, l1_sender: String, queue: String, status: String, updated_at: i64) -> OnchainActionHistoryEntry {
        OnchainActionHistoryEntry {
            acc,
            action_id,
            action_type,
            action_type_label,
            block_number,
            data,
            error_code: None,
            error_message: None,
            fallback_at: None,
            first_failed_at: None,
            l1_sender,
            last_failed_at: None,
            op_uuid: None,
            queue,
            status,
            tx_hash: None,
            updated_at,
        }
    }
}

