/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenInterestStats {
    #[serde(rename = "current_open_interest")]
    pub current_open_interest: String,
    #[serde(rename = "interest_cap")]
    pub interest_cap: String,
}

impl OpenInterestStats {
    pub fn new(current_open_interest: String, interest_cap: String) -> OpenInterestStats {
        OpenInterestStats {
            current_open_interest,
            interest_cap,
        }
    }
}

