/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionSettlementHistoryResponse {
    #[serde(rename = "settlements")]
    pub settlements: Vec<models::OptionSettlementResponse>,
}

impl OptionSettlementHistoryResponse {
    pub fn new(settlements: Vec<models::OptionSettlementResponse>) -> OptionSettlementHistoryResponse {
        OptionSettlementHistoryResponse {
            settlements,
        }
    }
}

