/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionDetails {
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "index")]
    pub index: String,
    #[serde(rename = "option_type")]
    pub option_type: String,
    #[serde(rename = "settlement_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub settlement_price: Option<Option<String>>,
    #[serde(rename = "strike")]
    pub strike: String,
}

impl OptionDetails {
    pub fn new(expiry: i32, index: String, option_type: String, strike: String) -> OptionDetails {
        OptionDetails {
            expiry,
            index,
            option_type,
            settlement_price: None,
            strike,
        }
    }
}

