/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionPricing {
    /// Implied volatility of the current best ask.
    #[serde(rename = "ai")]
    pub ai: String,
    /// Implied volatility of the current best bid.
    #[serde(rename = "bi")]
    pub bi: String,
    /// Delta of the option.
    #[serde(rename = "d")]
    pub d: String,
    /// Discount factor used to calculate the option premium.
    #[serde(rename = "df")]
    pub df: String,
    /// Forward price used to calculate the option premium.
    #[serde(rename = "f")]
    pub f: String,
    /// Gamma of the option.
    #[serde(rename = "g")]
    pub g: String,
    /// Implied volatility of the option.
    #[serde(rename = "i")]
    pub i: String,
    /// Mark price of the option.
    #[serde(rename = "m")]
    pub m: String,
    /// Rho of the option.
    #[serde(rename = "r")]
    pub r: String,
    /// Theta of the option.
    #[serde(rename = "t")]
    pub t: String,
    /// Vega of the option.
    #[serde(rename = "v")]
    pub v: String,
}

impl OptionPricing {
    pub fn new(ai: String, bi: String, d: String, df: String, f: String, g: String, i: String, m: String, r: String, t: String, v: String) -> OptionPricing {
        OptionPricing {
            ai,
            bi,
            d,
            df,
            f,
            g,
            i,
            m,
            r,
            t,
            v,
        }
    }
}

