/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptionSettlementResponse : One settled option position.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionSettlementResponse {
    /// Settled balance (negative = short, positive = long).
    #[serde(rename = "amount")]
    pub amount: String,
    /// Expiry of the option, unix seconds.
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "settlement_price")]
    pub settlement_price: String,
    /// Crystallized cash value = intrinsic value * amount.
    #[serde(rename = "settlement_value")]
    pub settlement_value: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl OptionSettlementResponse {
    /// One settled option position.
    pub fn new(amount: String, expiry: i32, instrument_name: String, settlement_price: String, settlement_value: String, subaccount_id: i32) -> OptionSettlementResponse {
        OptionSettlementResponse {
            amount,
            expiry,
            instrument_name,
            settlement_price,
            settlement_value,
            subaccount_id,
        }
    }
}

