/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderQuoteResponse : Estimated fill price, fees, and resulting margin for a proposed order — a non-binding dry-run. All price, fee, and margin fields are decimal strings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderQuoteResponse {
    #[serde(rename = "estimated_fee")]
    pub estimated_fee: String,
    #[serde(rename = "estimated_fill_amount")]
    pub estimated_fill_amount: String,
    #[serde(rename = "estimated_fill_price")]
    pub estimated_fill_price: String,
    #[serde(rename = "estimated_order_status")]
    pub estimated_order_status: models::OrderStatus,
    #[serde(rename = "estimated_realized_pnl")]
    pub estimated_realized_pnl: String,
    #[serde(rename = "estimated_realized_pnl_excl_fees")]
    pub estimated_realized_pnl_excl_fees: String,
    #[serde(rename = "invalid_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invalid_reason: Option<Option<String>>,
    #[serde(rename = "is_valid")]
    pub is_valid: bool,
    #[serde(rename = "max_amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_amount: Option<Option<String>>,
    #[serde(rename = "post_initial_margin")]
    pub post_initial_margin: String,
    #[serde(rename = "post_liquidation_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub post_liquidation_price: Option<Option<String>>,
    #[serde(rename = "pre_initial_margin")]
    pub pre_initial_margin: String,
    #[serde(rename = "suggested_max_fee")]
    pub suggested_max_fee: String,
}

impl OrderQuoteResponse {
    /// Estimated fill price, fees, and resulting margin for a proposed order — a non-binding dry-run. All price, fee, and margin fields are decimal strings.
    pub fn new(estimated_fee: String, estimated_fill_amount: String, estimated_fill_price: String, estimated_order_status: models::OrderStatus, estimated_realized_pnl: String, estimated_realized_pnl_excl_fees: String, is_valid: bool, post_initial_margin: String, pre_initial_margin: String, suggested_max_fee: String) -> OrderQuoteResponse {
        OrderQuoteResponse {
            estimated_fee,
            estimated_fill_amount,
            estimated_fill_price,
            estimated_order_status,
            estimated_realized_pnl,
            estimated_realized_pnl_excl_fees,
            invalid_reason: None,
            is_valid,
            max_amount: None,
            post_initial_margin,
            post_liquidation_price: None,
            pre_initial_margin,
            suggested_max_fee,
        }
    }
}

