/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderDebugResponse : Debug-route payload for one rebuilt action: the EIP-712 hashes plus the action input fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDebugResponse {
    /// EIP-712 struct hash of the `Action`: `keccak256(abi.encode(action_typehash, …, encoded_data_hashed, …))`.
    #[serde(rename = "action_hash")]
    pub action_hash: String,
    /// `ACTION_TYPEHASH` — keccak of the `Action` struct type string; invariant across deployments.
    #[serde(rename = "action_typehash")]
    pub action_typehash: String,
    /// EIP-712 domain separator of the Matching contract for this deployment.
    #[serde(rename = "domain_separator")]
    pub domain_separator: String,
    /// ABI-encoded, module-specific action payload (the `data` bytes), 0x-hex.
    #[serde(rename = "encoded_data")]
    pub encoded_data: String,
    /// `keccak256(encoded_data)` — the value packed into the struct hash.
    #[serde(rename = "encoded_data_hashed")]
    pub encoded_data_hashed: String,
    /// The signer the signature is checked against.
    #[serde(rename = "expected_signer")]
    pub expected_signer: String,
    /// The rebuilt `Action` envelope and its decoded module-specific `data`.
    #[serde(rename = "input_data")]
    pub input_data: models::OrderActionInputData,
    /// Per-action module contract address bound into the signed struct.
    #[serde(rename = "module")]
    pub module: String,
    /// Wallet that owns the subaccount the action applies to.
    #[serde(rename = "owner")]
    pub owner: String,
    /// null on the debug routes (no signature is checked there); on a signature-mismatch error this is the address actually recovered.
    #[serde(rename = "recovered_signer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recovered_signer: Option<Option<String>>,
    /// Final EIP-712 digest the client signs: `keccak256(0x1901 || domain_separator || action_hash)`.
    #[serde(rename = "typed_data_hash")]
    pub typed_data_hash: String,
}

impl OrderDebugResponse {
    /// Debug-route payload for one rebuilt action: the EIP-712 hashes plus the action input fields.
    pub fn new(action_hash: String, action_typehash: String, domain_separator: String, encoded_data: String, encoded_data_hashed: String, expected_signer: String, input_data: models::OrderActionInputData, module: String, owner: String, typed_data_hash: String) -> OrderDebugResponse {
        OrderDebugResponse {
            action_hash,
            action_typehash,
            domain_separator,
            encoded_data,
            encoded_data_hashed,
            expected_signer,
            input_data,
            module,
            owner,
            recovered_signer: None,
            typed_data_hash,
        }
    }
}

