/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    #[serde(rename = "algo_duration_sec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_duration_sec: Option<Option<i32>>,
    #[serde(rename = "algo_num_slices", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_num_slices: Option<Option<i32>>,
    #[serde(rename = "algo_slices_completed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_slices_completed: Option<Option<i32>>,
    #[serde(rename = "algo_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algo_type: Option<Option<models::AlgoType>>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "average_price")]
    pub average_price: bigdecimal::BigDecimal,
    #[serde(rename = "cancel_reason", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<models::CancelReason>,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee")]
    pub extra_fee: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "filled_amount")]
    pub filled_amount: bigdecimal::BigDecimal,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "is_transfer")]
    pub is_transfer: bool,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: i64,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "limit_price")]
    pub limit_price: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "mmp")]
    pub mmp: bool,
    #[serde(rename = "nonce")]
    pub nonce: String,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "order_fee")]
    pub order_fee: bigdecimal::BigDecimal,
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "order_status")]
    pub order_status: models::OrderStatus,
    #[serde(rename = "order_type")]
    pub order_type: models::OrderType,
    /// Optional UUID v4 string
    #[serde(rename = "quote_id", deserialize_with = "Option::deserialize")]
    pub quote_id: Option<uuid::Uuid>,
    /// Optional UUID v4 string
    #[serde(rename = "replaced_order_id", deserialize_with = "Option::deserialize")]
    pub replaced_order_id: Option<uuid::Uuid>,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "signed_limit_price", deserialize_with = "Option::deserialize")]
    pub signed_limit_price: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "time_in_force")]
    pub time_in_force: models::TimeInForce,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "trigger_price", deserialize_with = "Option::deserialize")]
    pub trigger_price: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "trigger_price_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_price_type: Option<Option<models::TriggerPriceType>>,
    #[serde(rename = "trigger_reject_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_reject_message: Option<Option<String>>,
    #[serde(rename = "trigger_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_type: Option<Option<models::TriggerType>>,
}

impl Order {
    pub fn new(amount: bigdecimal::BigDecimal, average_price: bigdecimal::BigDecimal, creation_timestamp: i64, direction: models::Direction, extra_fee: bigdecimal::BigDecimal, filled_amount: bigdecimal::BigDecimal, instrument_name: String, is_transfer: bool, last_update_timestamp: i64, limit_price: bigdecimal::BigDecimal, max_fee: bigdecimal::BigDecimal, mmp: bool, nonce: String, order_fee: bigdecimal::BigDecimal, order_id: String, order_status: models::OrderStatus, order_type: models::OrderType, quote_id: Option<uuid::Uuid>, replaced_order_id: Option<uuid::Uuid>, signature: String, signature_expiry_sec: i64, signed_limit_price: Option<bigdecimal::BigDecimal>, signer: String, subaccount_id: i64, time_in_force: models::TimeInForce, trigger_price: Option<bigdecimal::BigDecimal>) -> Order {
        Order {
            algo_duration_sec: None,
            algo_num_slices: None,
            algo_slices_completed: None,
            algo_type: None,
            amount,
            average_price,
            cancel_reason: None,
            creation_timestamp,
            direction,
            extra_fee,
            filled_amount,
            instrument_name,
            is_transfer,
            label: None,
            last_update_timestamp,
            limit_price,
            max_fee,
            mmp,
            nonce,
            order_fee,
            order_id,
            order_status,
            order_type,
            quote_id,
            replaced_order_id,
            signature,
            signature_expiry_sec,
            signed_limit_price,
            signer,
            subaccount_id,
            time_in_force,
            trigger_price,
            trigger_price_type: None,
            trigger_reject_message: None,
            trigger_type: None,
        }
    }
}

