/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCreatedResponse {
    #[serde(rename = "order")]
    pub order: models::Order,
    #[serde(rename = "trades")]
    pub trades: Vec<models::Trade>,
}

impl OrderCreatedResponse {
    pub fn new(order: models::Order, trades: Vec<models::Trade>) -> OrderCreatedResponse {
        OrderCreatedResponse {
            order,
            trades,
        }
    }
}

