/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderActionDataResponse {
    #[serde(rename = "asset_address")]
    pub asset_address: String,
    #[serde(rename = "asset_sub_id")]
    pub asset_sub_id: String,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "desired_amount")]
    pub desired_amount: bigdecimal::BigDecimal,
    #[serde(rename = "is_bid")]
    pub is_bid: bool,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "limit_price")]
    pub limit_price: bigdecimal::BigDecimal,
    #[serde(rename = "recipient_id")]
    pub recipient_id: i32,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "worst_fee")]
    pub worst_fee: bigdecimal::BigDecimal,
}

impl OrderActionDataResponse {
    pub fn new(asset_address: String, asset_sub_id: String, desired_amount: bigdecimal::BigDecimal, is_bid: bool, limit_price: bigdecimal::BigDecimal, recipient_id: i32, worst_fee: bigdecimal::BigDecimal) -> OrderActionDataResponse {
        OrderActionDataResponse {
            asset_address,
            asset_sub_id,
            desired_amount,
            is_bid,
            limit_price,
            recipient_id,
            worst_fee,
        }
    }
}

