/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderActionInputData : The `Action` envelope a debug route rebuilt from the request inputs, plus its decoded action data — i.e. what the signature commits to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderActionInputData {
    #[serde(rename = "data")]
    pub data: models::OrderActionDataResponse,
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "module")]
    pub module: String,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl OrderActionInputData {
    /// The `Action` envelope a debug route rebuilt from the request inputs, plus its decoded action data — i.e. what the signature commits to.
    pub fn new(data: models::OrderActionDataResponse, expiry: i32, module: String, nonce: i32, owner: String, signer: String, subaccount_id: i32) -> OrderActionInputData {
        OrderActionInputData {
            data,
            expiry,
            module,
            nonce,
            owner,
            signer,
            subaccount_id,
        }
    }
}

