/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderQuoteRequest : Parameters for `public/order_quote` and `private/order_quote`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderQuoteRequest {
    /// Order amount in units of the base, as a decimal string (e.g. `\"1.5\"`) or a JSON number.
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    /// Order direction
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Optional extra fee per unit of volume, as a decimal string or JSON number. Defaults to zero.
    #[serde(rename = "extra_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_fee: Option<Option<bigdecimal::BigDecimal>>,
    /// Instrument name
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "is_atomic_signing", skip_serializing_if = "Option::is_none")]
    pub is_atomic_signing: Option<bool>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Limit price in quote currency, as a decimal string or a JSON number.
    #[serde(rename = "limit_price")]
    pub limit_price: bigdecimal::BigDecimal,
    /// Max fee per unit of volume in quote currency, as a decimal string or a JSON number.
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "mmp", skip_serializing_if = "Option::is_none")]
    pub mmp: Option<bool>,
    /// Nonce.
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "order_type", skip_serializing_if = "Option::is_none")]
    pub order_type: Option<models::OrderType>,
    #[serde(rename = "reduce_only", skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    #[serde(rename = "referral_code", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<String>,
    #[serde(rename = "reject_post_only", skip_serializing_if = "Option::is_none")]
    pub reject_post_only: Option<bool>,
    #[serde(rename = "reject_timestamp", skip_serializing_if = "Option::is_none")]
    pub reject_timestamp: Option<i64>,
    /// Ethereum signature of the order.
    #[serde(rename = "signature")]
    pub signature: String,
    /// Signature expiry (unix seconds).
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    /// Owner wallet or session key that signed the order.
    #[serde(rename = "signer")]
    pub signer: String,
    /// Subaccount ID
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "time_in_force", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<models::TimeInForce>,
    /// Trigger price as a decimal string or JSON number; omit for non-trigger orders.
    #[serde(rename = "trigger_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_price: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "trigger_price_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_price_type: Option<Option<models::TriggerPriceType>>,
    #[serde(rename = "trigger_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_type: Option<Option<models::TriggerType>>,
}

impl OrderQuoteRequest {
    /// Parameters for `public/order_quote` and `private/order_quote`.
    pub fn new(amount: bigdecimal::BigDecimal, direction: models::Direction, instrument_name: String, limit_price: bigdecimal::BigDecimal, max_fee: bigdecimal::BigDecimal, nonce: String, signature: String, signature_expiry_sec: i64, signer: String, subaccount_id: i64) -> OrderQuoteRequest {
        OrderQuoteRequest {
            amount,
            client: None,
            direction,
            extra_fee: None,
            instrument_name,
            is_atomic_signing: None,
            label: None,
            limit_price,
            max_fee,
            mmp: None,
            nonce,
            order_type: None,
            reduce_only: None,
            referral_code: None,
            reject_post_only: None,
            reject_timestamp: None,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
            time_in_force: None,
            trigger_price: None,
            trigger_price_type: None,
            trigger_type: None,
        }
    }
}

