/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedVaultActions {
    #[serde(rename = "actions")]
    pub actions: Vec<models::VaultActionResponse>,
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl PaginatedVaultActions {
    pub fn new(actions: Vec<models::VaultActionResponse>, pagination: models::Pagination, wallet: String) -> PaginatedVaultActions {
        PaginatedVaultActions {
            actions,
            pagination,
            wallet,
        }
    }
}

