/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Pagination : Response envelope for paginated RPCs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "num_pages")]
    pub num_pages: i32,
}

impl Pagination {
    /// Response envelope for paginated RPCs.
    pub fn new(count: i32, num_pages: i32) -> Pagination {
        Pagination {
            count,
            num_pages,
        }
    }
}

