/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingDepositEntry {
    /// Per-queue id assigned by the `OnchainActionManager`; `0` for fast deposits (indexed from the factory event, not the pooled OAM action).
    #[serde(rename = "action_id")]
    pub action_id: i32,
    /// `Deposit` (existing subaccount), `DepositToNewSubaccount`, or `FastDeposit` (pooled, credited off-chain).
    #[serde(rename = "action_type")]
    pub action_type: String,
    /// Amount in the asset's native ERC-20 units, as a decimal string.
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "block_number")]
    pub block_number: i32,
    /// Fast only: the credit transfer's nonce, disambiguating a deposit's entries. Absent on slow entries and the uncredited remainder. Decimal string — the value exceeds JS number precision.
    #[serde(rename = "credit_nonce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub credit_nonce: Option<Option<String>>,
    /// `slow` or `fast`.
    #[serde(rename = "deposit_type")]
    pub deposit_type: String,
    #[serde(rename = "log_index")]
    pub log_index: i32,
    /// Manager of the new subaccount; `0` for existing-subaccount deposits.
    #[serde(rename = "manager_id")]
    pub manager_id: i32,
    /// `detected` (transfer seen at the tip, pre-confirmation) `pending` (escrow swept, awaiting confirmation) `confirmed` (sweep tx past the confirmation range) `reverted` (the sweep reorged out — or uncreditable: no valid destination exists) Fast deposits additionally show: `crediting` (transfer in flight), `credited` (paid out) `partial_revert` (reorged out after a chunk was paid)
    #[serde(rename = "status")]
    pub status: String,
    /// Credited subaccount; `0` for new-subaccount deposits.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    /// Milliseconds when the tracker first picked up the deposit - approximates the block timestamp of `block_number`. Shared by all of a deposit's entries.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "tx_hash")]
    pub tx_hash: String,
    #[serde(rename = "updated_at_ms")]
    pub updated_at_ms: i64,
}

impl PendingDepositEntry {
    pub fn new(action_id: i32, action_type: String, amount: String, asset: String, block_number: i32, deposit_type: String, log_index: i32, manager_id: i32, status: String, subaccount_id: i64, timestamp: i64, tx_hash: String, updated_at_ms: i64) -> PendingDepositEntry {
        PendingDepositEntry {
            action_id,
            action_type,
            amount,
            asset,
            block_number,
            credit_nonce: None,
            deposit_type,
            log_index,
            manager_id,
            status,
            subaccount_id,
            timestamp,
            tx_hash,
            updated_at_ms,
        }
    }
}

