/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PerformanceResolution : Quantization of the hourly samples, requested by the caller.
/// Quantization of the hourly samples, requested by the caller.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PerformanceResolution {
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "8h")]
    Variant8h,
    #[serde(rename = "24h")]
    Variant24h,
    #[serde(rename = "1wk")]
    Variant1wk,

}

impl std::fmt::Display for PerformanceResolution {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1h => write!(f, "1h"),
            Self::Variant8h => write!(f, "8h"),
            Self::Variant24h => write!(f, "24h"),
            Self::Variant1wk => write!(f, "1wk"),
        }
    }
}

impl Default for PerformanceResolution {
    fn default() -> PerformanceResolution {
        Self::Variant1h
    }
}

