/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerpDetails {
    #[serde(rename = "aggregate_funding")]
    pub aggregate_funding: String,
    #[serde(rename = "funding_rate")]
    pub funding_rate: String,
    #[serde(rename = "index")]
    pub index: String,
    #[serde(rename = "max_rate_per_hour")]
    pub max_rate_per_hour: String,
    #[serde(rename = "min_rate_per_hour")]
    pub min_rate_per_hour: String,
    #[serde(rename = "static_interest_rate")]
    pub static_interest_rate: String,
}

impl PerpDetails {
    pub fn new(aggregate_funding: String, funding_rate: String, index: String, max_rate_per_hour: String, min_rate_per_hour: String, static_interest_rate: String) -> PerpDetails {
        PerpDetails {
            aggregate_funding,
            funding_rate,
            index,
            max_rate_per_hour,
            min_rate_per_hour,
            static_interest_rate,
        }
    }
}

