/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerpFeedDataResponse {
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deadline")]
    pub deadline: i32,
    #[serde(rename = "signatures")]
    pub signatures: models::OracleSignatureDataResponse,
    #[serde(rename = "spot_diff_value")]
    pub spot_diff_value: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PerpFeedDataResponse {
    pub fn new(confidence: String, currency: String, deadline: i32, signatures: models::OracleSignatureDataResponse, spot_diff_value: String, timestamp: i32, r#type: String) -> PerpFeedDataResponse {
        PerpFeedDataResponse {
            confidence,
            currency,
            deadline,
            signatures,
            spot_diff_value,
            timestamp,
            r#type,
        }
    }
}

