/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerpSettlementEventResponse {
    #[serde(rename = "batch_status")]
    pub batch_status: models::BatchStatus,
    /// UUID of the settlement batch; a settlement in a reverted or errored batch reflects that status.
    #[serde(rename = "batch_uuid")]
    pub batch_uuid: String,
    #[serde(rename = "funding")]
    pub funding: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "pnl")]
    pub pnl: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
}

impl PerpSettlementEventResponse {
    pub fn new(batch_status: models::BatchStatus, batch_uuid: String, funding: String, instrument_name: String, pnl: String, subaccount_id: i32, timestamp: i64) -> PerpSettlementEventResponse {
        PerpSettlementEventResponse {
            batch_status,
            batch_uuid,
            funding,
            instrument_name,
            pnl,
            subaccount_id,
            timestamp,
            tx_hash: None,
        }
    }
}

