/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollRfqsRequest {
    #[serde(rename = "from_timestamp", skip_serializing_if = "Option::is_none")]
    pub from_timestamp: Option<i64>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "rfq_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rfq_id: Option<Option<String>>,
    #[serde(rename = "rfq_subaccount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rfq_subaccount_id: Option<Option<i64>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "to_timestamp", skip_serializing_if = "Option::is_none")]
    pub to_timestamp: Option<i64>,
}

impl PollRfqsRequest {
    pub fn new(subaccount_id: i64) -> PollRfqsRequest {
        PollRfqsRequest {
            from_timestamp: None,
            page: None,
            page_size: None,
            rfq_id: None,
            rfq_subaccount_id: None,
            status: None,
            subaccount_id,
            to_timestamp: None,
        }
    }
}

