/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Position {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "amount_step")]
    pub amount_step: String,
    #[serde(rename = "average_price")]
    pub average_price: String,
    #[serde(rename = "average_price_excl_fees")]
    pub average_price_excl_fees: String,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "cumulative_funding")]
    pub cumulative_funding: String,
    #[serde(rename = "delta")]
    pub delta: String,
    #[serde(rename = "gamma")]
    pub gamma: String,
    #[serde(rename = "index_price")]
    pub index_price: String,
    #[serde(rename = "initial_margin")]
    pub initial_margin: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "instrument_type")]
    pub instrument_type: String,
    #[serde(rename = "leverage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub leverage: Option<Option<String>>,
    #[serde(rename = "liquidation_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub liquidation_price: Option<Option<String>>,
    #[serde(rename = "maintenance_margin")]
    pub maintenance_margin: String,
    #[serde(rename = "mark_price")]
    pub mark_price: String,
    #[serde(rename = "mark_value")]
    pub mark_value: String,
    #[serde(rename = "net_settlements")]
    pub net_settlements: String,
    #[serde(rename = "open_orders_margin")]
    pub open_orders_margin: String,
    #[serde(rename = "pending_funding")]
    pub pending_funding: String,
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: String,
    #[serde(rename = "realized_pnl_excl_fees")]
    pub realized_pnl_excl_fees: String,
    #[serde(rename = "theta")]
    pub theta: String,
    #[serde(rename = "total_fees")]
    pub total_fees: String,
    #[serde(rename = "unrealized_pnl")]
    pub unrealized_pnl: String,
    #[serde(rename = "unrealized_pnl_excl_fees")]
    pub unrealized_pnl_excl_fees: String,
    #[serde(rename = "vega")]
    pub vega: String,
}

impl Position {
    pub fn new(amount: String, amount_step: String, average_price: String, average_price_excl_fees: String, creation_timestamp: i64, cumulative_funding: String, delta: String, gamma: String, index_price: String, initial_margin: String, instrument_name: String, instrument_type: String, maintenance_margin: String, mark_price: String, mark_value: String, net_settlements: String, open_orders_margin: String, pending_funding: String, realized_pnl: String, realized_pnl_excl_fees: String, theta: String, total_fees: String, unrealized_pnl: String, unrealized_pnl_excl_fees: String, vega: String) -> Position {
        Position {
            amount,
            amount_step,
            average_price,
            average_price_excl_fees,
            creation_timestamp,
            cumulative_funding,
            delta,
            gamma,
            index_price,
            initial_margin,
            instrument_name,
            instrument_type,
            leverage: None,
            liquidation_price: None,
            maintenance_margin,
            mark_price,
            mark_value,
            net_settlements,
            open_orders_margin,
            pending_funding,
            realized_pnl,
            realized_pnl_excl_fees,
            theta,
            total_fees,
            unrealized_pnl,
            unrealized_pnl_excl_fees,
            vega,
        }
    }
}

