/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateTransferSpotExternalRequest {
    /// Transfer amount in units of the asset, as a decimal string (e.g. `\"1.5\"`) or JSON number.
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    /// Maximum sequencer fee the signer authorises, in USD, as a decimal string (e.g. `\"1.5\"`) or a JSON number. Must cover both the transfer fee and any subaccount-creation fee.
    #[serde(rename = "max_fee_usd")]
    pub max_fee_usd: bigdecimal::BigDecimal,
    /// Manager id for the new subaccount when `to_subaccount_id == 0`.
    #[serde(rename = "new_subaccount_manager")]
    pub new_subaccount_manager: i32,
    #[serde(rename = "nonce")]
    pub nonce: i64,
    /// Owner of the destination account/subaccount.
    #[serde(rename = "recipient_address")]
    pub recipient_address: String,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "sub_id")]
    pub sub_id: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// Recipient's existing destination subaccount. `0` → create a new subaccount for `recipient_address` under `new_subaccount_manager`.
    #[serde(rename = "to_subaccount_id")]
    pub to_subaccount_id: i32,
}

impl PrivateTransferSpotExternalRequest {
    pub fn new(amount: bigdecimal::BigDecimal, asset_name: String, max_fee_usd: bigdecimal::BigDecimal, new_subaccount_manager: i32, nonce: i64, recipient_address: String, signature: String, signature_expiry_sec: i32, signer: String, sub_id: i32, subaccount_id: i32, to_subaccount_id: i32) -> PrivateTransferSpotExternalRequest {
        PrivateTransferSpotExternalRequest {
            amount,
            asset_name,
            max_fee_usd,
            new_subaccount_manager,
            nonce,
            recipient_address,
            signature,
            signature_expiry_sec,
            signer,
            sub_id,
            subaccount_id,
            to_subaccount_id,
        }
    }
}

