/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateCreateSessionKeyResponse {
    #[serde(rename = "expiry_sec")]
    pub expiry_sec: i32,
    #[serde(rename = "ip_whitelist")]
    pub ip_whitelist: Vec<String>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "offchain_scopes")]
    pub offchain_scopes: Vec<String>,
    #[serde(rename = "protocol_scopes")]
    pub protocol_scopes: Vec<String>,
    #[serde(rename = "public_session_key")]
    pub public_session_key: String,
    /// Subaccounts the key may act on. Empty/omitted request (all subaccounts) is expanded to the wallet's current subaccount list.
    #[serde(rename = "subaccount_ids")]
    pub subaccount_ids: Vec<i32>,
}

impl PrivateCreateSessionKeyResponse {
    pub fn new(expiry_sec: i32, ip_whitelist: Vec<String>, offchain_scopes: Vec<String>, protocol_scopes: Vec<String>, public_session_key: String, subaccount_ids: Vec<i32>) -> PrivateCreateSessionKeyResponse {
        PrivateCreateSessionKeyResponse {
            expiry_sec,
            ip_whitelist,
            label: None,
            offchain_scopes,
            protocol_scopes,
            public_session_key,
            subaccount_ids,
        }
    }
}

