/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGetPositionsResponse {
    #[serde(rename = "positions")]
    pub positions: Vec<models::Position>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl PrivateGetPositionsResponse {
    pub fn new(positions: Vec<models::Position>, subaccount_id: i32) -> PrivateGetPositionsResponse {
        PrivateGetPositionsResponse {
            positions,
            subaccount_id,
        }
    }
}

