/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGetSubaccountsResponse {
    #[serde(rename = "subaccount_ids")]
    pub subaccount_ids: Vec<i32>,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl PrivateGetSubaccountsResponse {
    pub fn new(subaccount_ids: Vec<i32>, wallet: String) -> PrivateGetSubaccountsResponse {
        PrivateGetSubaccountsResponse {
            subaccount_ids,
            wallet,
        }
    }
}

