/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGetAccountResponse {
    #[serde(rename = "cancel_on_disconnect")]
    pub cancel_on_disconnect: bool,
    #[serde(rename = "creation_timestamp_sec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creation_timestamp_sec: Option<Option<i32>>,
    #[serde(rename = "fee_info")]
    pub fee_info: models::AccountFeeInfo,
    #[serde(rename = "is_rfq_maker")]
    pub is_rfq_maker: bool,
    #[serde(rename = "per_endpoint_tps")]
    pub per_endpoint_tps: std::collections::HashMap<String, i32>,
    #[serde(rename = "referral_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<Option<String>>,
    #[serde(rename = "subaccount_ids")]
    pub subaccount_ids: Vec<i32>,
    #[serde(rename = "wallet")]
    pub wallet: String,
    #[serde(rename = "websocket_matching_tps")]
    pub websocket_matching_tps: i32,
    #[serde(rename = "websocket_non_matching_tps")]
    pub websocket_non_matching_tps: i32,
    #[serde(rename = "websocket_option_tps")]
    pub websocket_option_tps: i32,
    #[serde(rename = "websocket_perp_tps")]
    pub websocket_perp_tps: i32,
}

impl PrivateGetAccountResponse {
    pub fn new(cancel_on_disconnect: bool, fee_info: models::AccountFeeInfo, is_rfq_maker: bool, per_endpoint_tps: std::collections::HashMap<String, i32>, subaccount_ids: Vec<i32>, wallet: String, websocket_matching_tps: i32, websocket_non_matching_tps: i32, websocket_option_tps: i32, websocket_perp_tps: i32) -> PrivateGetAccountResponse {
        PrivateGetAccountResponse {
            cancel_on_disconnect,
            creation_timestamp_sec: None,
            fee_info,
            is_rfq_maker,
            per_endpoint_tps,
            referral_code: None,
            subaccount_ids,
            wallet,
            websocket_matching_tps,
            websocket_non_matching_tps,
            websocket_option_tps,
            websocket_perp_tps,
        }
    }
}

