/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateTransferSpotRequest {
    /// Transfer amount in units of the asset, as a decimal string (e.g. `\"1.5\"`) or JSON number.
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    /// Maximum sequencer fee the signer authorises, in USD, as a decimal string (e.g. `\"1.5\"`) or a JSON number.
    #[serde(rename = "max_fee_usd")]
    pub max_fee_usd: bigdecimal::BigDecimal,
    /// Non-zero → create a new sender-owned subaccount under this manager id.
    #[serde(rename = "new_subaccount_manager")]
    pub new_subaccount_manager: i32,
    #[serde(rename = "nonce")]
    pub nonce: i64,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "sub_id")]
    pub sub_id: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// Existing destination subaccount. Ignored when `new_subaccount_manager != 0`.
    #[serde(rename = "to_subaccount_id")]
    pub to_subaccount_id: i32,
}

impl PrivateTransferSpotRequest {
    pub fn new(amount: bigdecimal::BigDecimal, asset_name: String, max_fee_usd: bigdecimal::BigDecimal, new_subaccount_manager: i32, nonce: i64, signature: String, signature_expiry_sec: i32, signer: String, sub_id: i32, subaccount_id: i32, to_subaccount_id: i32) -> PrivateTransferSpotRequest {
        PrivateTransferSpotRequest {
            amount,
            asset_name,
            max_fee_usd,
            new_subaccount_manager,
            nonce,
            signature,
            signature_expiry_sec,
            signer,
            sub_id,
            subaccount_id,
            to_subaccount_id,
        }
    }
}

