/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGetCollateralsResponse {
    #[serde(rename = "collaterals")]
    pub collaterals: Vec<models::Collateral>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl PrivateGetCollateralsResponse {
    pub fn new(collaterals: Vec<models::Collateral>, subaccount_id: i32) -> PrivateGetCollateralsResponse {
        PrivateGetCollateralsResponse {
            collaterals,
            subaccount_id,
        }
    }
}

