/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateWithdrawResponse {
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
}

impl PrivateWithdrawResponse {
    pub fn new(op_uuid: String, operation_id: i32) -> PrivateWithdrawResponse {
        PrivateWithdrawResponse {
            op_uuid,
            operation_id,
        }
    }
}

