/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtocolVault {
    #[serde(rename = "closed")]
    pub closed: bool,
    #[serde(rename = "config")]
    pub config: models::VaultConfig,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "global_hwm")]
    pub global_hwm: bigdecimal::BigDecimal,
    #[serde(rename = "last_fee_settled_at_sec")]
    pub last_fee_settled_at_sec: i32,
    #[serde(rename = "protocol_fee_share_bps")]
    pub protocol_fee_share_bps: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "total_shares")]
    pub total_shares: bigdecimal::BigDecimal,
}

impl ProtocolVault {
    pub fn new(closed: bool, config: models::VaultConfig, global_hwm: bigdecimal::BigDecimal, last_fee_settled_at_sec: i32, protocol_fee_share_bps: i32, subaccount_id: i32, total_shares: bigdecimal::BigDecimal) -> ProtocolVault {
        ProtocolVault {
            closed,
            config,
            global_hwm,
            last_fee_settled_at_sec,
            protocol_fee_share_bps,
            subaccount_id,
            total_shares,
        }
    }
}

