/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicWithdrawDebugRequest {
    #[serde(rename = "amount_in_underlying")]
    pub amount_in_underlying: String,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    #[serde(rename = "force_batch")]
    pub force_batch: bool,
    /// Maximum sequencer fee the signer authorises, in USD, as a decimal string (e.g. `\"1.5\"`) or a JSON number.
    #[serde(rename = "max_fee_usd")]
    pub max_fee_usd: bigdecimal::BigDecimal,
    #[serde(rename = "nonce")]
    pub nonce: i64,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl PublicWithdrawDebugRequest {
    pub fn new(amount_in_underlying: String, asset_name: String, force_batch: bool, max_fee_usd: bigdecimal::BigDecimal, nonce: i64, signature_expiry_sec: i32, signer: String, subaccount_id: i32) -> PublicWithdrawDebugRequest {
        PublicWithdrawDebugRequest {
            amount_in_underlying,
            asset_name,
            force_batch,
            max_fee_usd,
            nonce,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

