/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicQuote {
    #[serde(rename = "cancel_reason")]
    pub cancel_reason: models::RfqCancelReason,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fill_pct")]
    pub fill_pct: bigdecimal::BigDecimal,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: i64,
    #[serde(rename = "legs")]
    pub legs: Vec<models::PricedLegParamsAndResponse>,
    #[serde(rename = "legs_hash")]
    pub legs_hash: String,
    #[serde(rename = "liquidity_role")]
    pub liquidity_role: models::LiquidityRole,
    /// UUID v4 string
    #[serde(rename = "quote_id")]
    pub quote_id: uuid::Uuid,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::RfqStatus,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl PublicQuote {
    pub fn new(cancel_reason: models::RfqCancelReason, creation_timestamp: i64, direction: models::Direction, fill_pct: bigdecimal::BigDecimal, last_update_timestamp: i64, legs: Vec<models::PricedLegParamsAndResponse>, legs_hash: String, liquidity_role: models::LiquidityRole, quote_id: uuid::Uuid, rfq_id: uuid::Uuid, status: models::RfqStatus, subaccount_id: i64, wallet: String) -> PublicQuote {
        PublicQuote {
            cancel_reason,
            creation_timestamp,
            direction,
            fill_pct,
            last_update_timestamp,
            legs,
            legs_hash,
            liquidity_role,
            quote_id,
            rfq_id,
            status,
            subaccount_id,
            wallet,
        }
    }
}

