/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicGetWalletsFromSessionKeyResponse {
    #[serde(rename = "wallets")]
    pub wallets: Vec<String>,
}

impl PublicGetWalletsFromSessionKeyResponse {
    pub fn new(wallets: Vec<String>) -> PublicGetWalletsFromSessionKeyResponse {
        PublicGetWalletsFromSessionKeyResponse {
            wallets,
        }
    }
}

