/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicVaultActionResponse : A vault action at the aggregate, vault level. Per-holder position details (entry/exit price, before/after balances) are omitted — those are available on the private endpoints. Monetary fields (share price, NAV, high-water marks) are decimal strings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicVaultActionResponse {
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "curator_shares_minted")]
    pub curator_shares_minted: bigdecimal::BigDecimal,
    /// Timestamp of this event (ms).
    #[serde(rename = "event_ts")]
    pub event_ts: i64,
    /// \"vault_deposit\" | \"vault_withdraw\" | \"vault_force_withdraw\".
    #[serde(rename = "event_type")]
    pub event_type: String,
    #[serde(rename = "holder")]
    pub holder: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "management_shares_minted")]
    pub management_shares_minted: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "nav")]
    pub nav: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "new_high_water_mark")]
    pub new_high_water_mark: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "old_high_water_mark")]
    pub old_high_water_mark: bigdecimal::BigDecimal,
    #[serde(rename = "operation_uuid")]
    pub operation_uuid: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "performance_shares_minted")]
    pub performance_shares_minted: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "protocol_shares_minted")]
    pub protocol_shares_minted: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "share_price")]
    pub share_price: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "shares_delta")]
    pub shares_delta: bigdecimal::BigDecimal,
    /// While the action is in the queue, one of: \"enqueued\" | \"sequencer_applied\" | \"user_cancel\" | \"curator_reject\" | \"protocol_reject\" | \"expired\".  Once the action is in the protocol, the status takes on `BatchStatus` values: \"Batching\" | \"Executing\" | \"Proving\" | \"Settling\" | \"Settled\" or an error.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "total_shares")]
    pub total_shares: bigdecimal::BigDecimal,
}

impl PublicVaultActionResponse {
    /// A vault action at the aggregate, vault level. Per-holder position details (entry/exit price, before/after balances) are omitted — those are available on the private endpoints. Monetary fields (share price, NAV, high-water marks) are decimal strings.
    pub fn new(curator_shares_minted: bigdecimal::BigDecimal, event_ts: i64, event_type: String, holder: String, management_shares_minted: bigdecimal::BigDecimal, nav: bigdecimal::BigDecimal, new_high_water_mark: bigdecimal::BigDecimal, old_high_water_mark: bigdecimal::BigDecimal, operation_uuid: String, performance_shares_minted: bigdecimal::BigDecimal, protocol_shares_minted: bigdecimal::BigDecimal, share_price: bigdecimal::BigDecimal, shares_delta: bigdecimal::BigDecimal, status: String, subaccount_id: i32, total_shares: bigdecimal::BigDecimal) -> PublicVaultActionResponse {
        PublicVaultActionResponse {
            curator_shares_minted,
            event_ts,
            event_type,
            holder,
            management_shares_minted,
            nav,
            new_high_water_mark,
            old_high_water_mark,
            operation_uuid,
            performance_shares_minted,
            protocol_shares_minted,
            share_price,
            shares_delta,
            status,
            subaccount_id,
            total_shares,
        }
    }
}

