/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicRfq {
    #[serde(rename = "cancel_reason")]
    pub cancel_reason: models::RfqCancelReason,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    /// Lifetime taker fill rate as a decimal string; null until the wallet has enough lifetime RFQs for the rate to be meaningful.
    #[serde(rename = "fill_rate", deserialize_with = "Option::deserialize")]
    pub fill_rate: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "filled_direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filled_direction: Option<Option<models::Direction>>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "filled_pct")]
    pub filled_pct: bigdecimal::BigDecimal,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: i64,
    #[serde(rename = "legs")]
    pub legs: Vec<models::LegUnpricedParams>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "partial_fill_step")]
    pub partial_fill_step: bigdecimal::BigDecimal,
    /// Decayed-recent taker fill rate as a decimal string; null until enough recent RFQ activity has accumulated for the rate to be meaningful.
    #[serde(rename = "recent_fill_rate", deserialize_with = "Option::deserialize")]
    pub recent_fill_rate: Option<bigdecimal::BigDecimal>,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::RfqStatus,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "total_cost", deserialize_with = "Option::deserialize")]
    pub total_cost: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "valid_until")]
    pub valid_until: i64,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl PublicRfq {
    pub fn new(cancel_reason: models::RfqCancelReason, creation_timestamp: i64, fill_rate: Option<bigdecimal::BigDecimal>, filled_pct: bigdecimal::BigDecimal, last_update_timestamp: i64, legs: Vec<models::LegUnpricedParams>, partial_fill_step: bigdecimal::BigDecimal, recent_fill_rate: Option<bigdecimal::BigDecimal>, rfq_id: uuid::Uuid, status: models::RfqStatus, subaccount_id: i64, total_cost: Option<bigdecimal::BigDecimal>, valid_until: i64, wallet: String) -> PublicRfq {
        PublicRfq {
            cancel_reason,
            creation_timestamp,
            fill_rate,
            filled_direction: None,
            filled_pct,
            last_update_timestamp,
            legs,
            partial_fill_step,
            recent_fill_rate,
            rfq_id,
            status,
            subaccount_id,
            total_cost,
            valid_until,
            wallet,
        }
    }
}

