/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteExecuteResponse {
    #[serde(rename = "cancel_reason")]
    pub cancel_reason: models::RfqCancelReason,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee")]
    pub extra_fee: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fee")]
    pub fee: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fill_pct")]
    pub fill_pct: bigdecimal::BigDecimal,
    #[serde(rename = "is_transfer")]
    pub is_transfer: bool,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: i64,
    #[serde(rename = "legs")]
    pub legs: Vec<models::PricedLegParamsAndResponse>,
    #[serde(rename = "legs_hash")]
    pub legs_hash: String,
    #[serde(rename = "liquidity_role")]
    pub liquidity_role: models::LiquidityRole,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "mmp")]
    pub mmp: bool,
    #[serde(rename = "nonce")]
    pub nonce: String,
    /// UUID v4 string
    #[serde(rename = "quote_id")]
    pub quote_id: uuid::Uuid,
    /// Cumulative fraction of the RFQ filled after this execution, as a decimal string (e.g. `\"0.5\"` = 50% filled).
    #[serde(rename = "rfq_filled_pct")]
    pub rfq_filled_pct: bigdecimal::BigDecimal,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    #[serde(rename = "status")]
    pub status: models::RfqStatus,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl QuoteExecuteResponse {
    pub fn new(cancel_reason: models::RfqCancelReason, creation_timestamp: i64, direction: models::Direction, extra_fee: bigdecimal::BigDecimal, fee: bigdecimal::BigDecimal, fill_pct: bigdecimal::BigDecimal, is_transfer: bool, label: String, last_update_timestamp: i64, legs: Vec<models::PricedLegParamsAndResponse>, legs_hash: String, liquidity_role: models::LiquidityRole, max_fee: bigdecimal::BigDecimal, mmp: bool, nonce: String, quote_id: uuid::Uuid, rfq_filled_pct: bigdecimal::BigDecimal, rfq_id: uuid::Uuid, signature_expiry_sec: i64, status: models::RfqStatus, subaccount_id: i64) -> QuoteExecuteResponse {
        QuoteExecuteResponse {
            cancel_reason,
            creation_timestamp,
            direction,
            extra_fee,
            fee,
            fill_pct,
            is_transfer,
            label,
            last_update_timestamp,
            legs,
            legs_hash,
            liquidity_role,
            max_fee,
            mmp,
            nonce,
            quote_id,
            rfq_filled_pct,
            rfq_id,
            signature_expiry_sec,
            status,
            subaccount_id,
        }
    }
}

