/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotePollResponse {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "quotes")]
    pub quotes: Vec<models::PublicQuote>,
}

impl QuotePollResponse {
    pub fn new(pagination: models::Pagination, quotes: Vec<models::PublicQuote>) -> QuotePollResponse {
        QuotePollResponse {
            pagination,
            quotes,
        }
    }
}

