/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteReplaceResponse {
    #[serde(rename = "cancelled_quote")]
    pub cancelled_quote: models::Quote,
    #[serde(rename = "create_quote_error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub create_quote_error: Option<Option<models::RpcError>>,
    #[serde(rename = "quote", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quote: Option<Option<models::Quote>>,
}

impl QuoteReplaceResponse {
    pub fn new(cancelled_quote: models::Quote) -> QuoteReplaceResponse {
        QuoteReplaceResponse {
            cancelled_quote,
            create_quote_error: None,
            quote: None,
        }
    }
}

