/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitInfo {
    /// Total consumed points.
    #[serde(rename = "consumedPoints")]
    pub consumed_points: i64,
    /// Whether it's the first request in this duration window.
    #[serde(rename = "isFirstInDuration")]
    pub is_first_in_duration: bool,
    /// Milliseconds before the next request is allowed (0 if none).
    #[serde(rename = "msBeforeNext")]
    pub ms_before_next: i32,
    /// Number of remaining points (tokens).
    #[serde(rename = "remainingPoints")]
    pub remaining_points: i64,
}

impl RateLimitInfo {
    pub fn new(consumed_points: i64, is_first_in_duration: bool, ms_before_next: i32, remaining_points: i64) -> RateLimitInfo {
        RateLimitInfo {
            consumed_points,
            is_first_in_duration,
            ms_before_next,
            remaining_points,
        }
    }
}

