/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateFeedDataResponse {
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deadline")]
    pub deadline: i32,
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "rate")]
    pub rate: String,
    #[serde(rename = "signatures")]
    pub signatures: models::OracleSignatureDataResponse,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl RateFeedDataResponse {
    pub fn new(confidence: String, currency: String, deadline: i32, expiry: i32, rate: String, signatures: models::OracleSignatureDataResponse, timestamp: i32) -> RateFeedDataResponse {
        RateFeedDataResponse {
            confidence,
            currency,
            deadline,
            expiry,
            rate,
            signatures,
            timestamp,
        }
    }
}

