/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralPerformanceByInstrumentType : Referral performance for one `(role, currency, instrument_type)` bucket.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralPerformanceByInstrumentType {
    #[serde(rename = "builder_fee")]
    pub builder_fee: String,
    #[serde(rename = "fee_reward")]
    pub fee_reward: String,
    #[serde(rename = "notional_volume")]
    pub notional_volume: String,
    #[serde(rename = "referred_fee")]
    pub referred_fee: String,
    #[serde(rename = "unique_traders_referred")]
    pub unique_traders_referred: i32,
}

impl ReferralPerformanceByInstrumentType {
    /// Referral performance for one `(role, currency, instrument_type)` bucket.
    pub fn new(builder_fee: String, fee_reward: String, notional_volume: String, referred_fee: String, unique_traders_referred: i32) -> ReferralPerformanceByInstrumentType {
        ReferralPerformanceByInstrumentType {
            builder_fee,
            fee_reward,
            notional_volume,
            referred_fee,
            unique_traders_referred,
        }
    }
}

