/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Referrer {
    #[serde(rename = "receiving_wallet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receiving_wallet: Option<Option<String>>,
    #[serde(rename = "referral_code")]
    pub referral_code: String,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl Referrer {
    pub fn new(referral_code: String, wallet: String) -> Referrer {
        Referrer {
            receiving_wallet: None,
            referral_code,
            wallet,
        }
    }
}

