/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterDepositAddressParams {
    /// Which factory to register against. Required: the same `(wallet, subaccount, manager)` has a distinct escrow address per factory, so callers must always be explicit about which flow they want.
    #[serde(rename = "deposit_type")]
    pub deposit_type: models::DepositType,
    /// Manager the deposit routes under. Required (non-zero) when creating a new subaccount (`subaccount_id` omitted or 0); must be 0 or omitted for an existing subaccount — it salts the deposit address, so a nonzero value would mint a distinct escrow for the same destination.
    #[serde(rename = "manager_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub manager_id: Option<Option<i32>>,
    #[serde(rename = "subaccount_id", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<i64>,
    /// Wallet address to watch for deposits.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl RegisterDepositAddressParams {
    pub fn new(deposit_type: models::DepositType, wallet: String) -> RegisterDepositAddressParams {
        RegisterDepositAddressParams {
            deposit_type,
            manager_id: None,
            subaccount_id: None,
            wallet,
        }
    }
}

