/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceOrderResponse {
    #[serde(rename = "cancelled_order", deserialize_with = "Option::deserialize")]
    pub cancelled_order: Option<models::Order>,
    #[serde(rename = "create_order_error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub create_order_error: Option<Option<models::RpcError>>,
    #[serde(rename = "order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order: Option<Option<models::Order>>,
    #[serde(rename = "trades", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trades: Option<Option<Vec<models::Trade>>>,
}

impl ReplaceOrderResponse {
    pub fn new(cancelled_order: Option<models::Order>) -> ReplaceOrderResponse {
        ReplaceOrderResponse {
            cancelled_order,
            create_order_error: None,
            order: None,
            trades: None,
        }
    }
}

