/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestVaultWithdrawRequest : Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestVaultWithdrawRequest {
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// Number of vault shares to burn, as a decimal string.
    #[serde(rename = "shares_to_burn")]
    pub shares_to_burn: bigdecimal::BigDecimal,
    /// 0x-prefixed hex of the 65-byte EOA signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The subaccount the action is signed on; which subaccount applies depends on the specific method — see that method's reference.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "vault_subaccount_id")]
    pub vault_subaccount_id: i32,
}

impl RequestVaultWithdrawRequest {
    /// Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
    pub fn new(nonce: i32, shares_to_burn: bigdecimal::BigDecimal, signature: String, signature_expiry_sec: i32, signer: String, subaccount_id: i32, vault_subaccount_id: i32) -> RequestVaultWithdrawRequest {
        RequestVaultWithdrawRequest {
            nonce,
            shares_to_burn,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
            vault_subaccount_id,
        }
    }
}

