/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestVaultDepositRequest : Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestVaultDepositRequest {
    /// Deposit amount in the vault's deposit asset, as a decimal string (e.g. `\"1\"`).
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "deposit_spot_asset")]
    pub deposit_spot_asset: String,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// 0x-prefixed hex of the 65-byte EOA signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The subaccount the action is signed on; which subaccount applies depends on the specific method — see that method's reference.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "vault_subaccount_id")]
    pub vault_subaccount_id: i32,
}

impl RequestVaultDepositRequest {
    /// Fields common to every signed vault action. They appear alongside each endpoint's action-specific parameters in the same request object.
    pub fn new(amount: bigdecimal::BigDecimal, deposit_spot_asset: String, nonce: i32, signature: String, signature_expiry_sec: i32, signer: String, subaccount_id: i32, vault_subaccount_id: i32) -> RequestVaultDepositRequest {
        RequestVaultDepositRequest {
            amount,
            deposit_spot_asset,
            nonce,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
            vault_subaccount_id,
        }
    }
}

