/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rfq {
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "ask_total_cost", deserialize_with = "Option::deserialize")]
    pub ask_total_cost: Option<bigdecimal::BigDecimal>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "bid_total_cost", deserialize_with = "Option::deserialize")]
    pub bid_total_cost: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "cancel_reason")]
    pub cancel_reason: models::RfqCancelReason,
    #[serde(rename = "counterparties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub counterparties: Option<Option<Vec<String>>>,
    #[serde(rename = "creation_timestamp")]
    pub creation_timestamp: i64,
    #[serde(rename = "filled_direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filled_direction: Option<Option<models::Direction>>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "filled_pct")]
    pub filled_pct: bigdecimal::BigDecimal,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: i64,
    #[serde(rename = "legs")]
    pub legs: Vec<models::LegUnpricedParams>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "mark_total_cost", deserialize_with = "Option::deserialize")]
    pub mark_total_cost: Option<bigdecimal::BigDecimal>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "max_total_cost", deserialize_with = "Option::deserialize")]
    pub max_total_cost: Option<bigdecimal::BigDecimal>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "min_total_cost", deserialize_with = "Option::deserialize")]
    pub min_total_cost: Option<bigdecimal::BigDecimal>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "partial_fill_step")]
    pub partial_fill_step: bigdecimal::BigDecimal,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::RfqStatus,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "total_cost", deserialize_with = "Option::deserialize")]
    pub total_cost: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "valid_until")]
    pub valid_until: i64,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl Rfq {
    pub fn new(ask_total_cost: Option<bigdecimal::BigDecimal>, bid_total_cost: Option<bigdecimal::BigDecimal>, cancel_reason: models::RfqCancelReason, creation_timestamp: i64, filled_pct: bigdecimal::BigDecimal, label: String, last_update_timestamp: i64, legs: Vec<models::LegUnpricedParams>, mark_total_cost: Option<bigdecimal::BigDecimal>, max_total_cost: Option<bigdecimal::BigDecimal>, min_total_cost: Option<bigdecimal::BigDecimal>, partial_fill_step: bigdecimal::BigDecimal, rfq_id: uuid::Uuid, status: models::RfqStatus, subaccount_id: i64, total_cost: Option<bigdecimal::BigDecimal>, valid_until: i64, wallet: String) -> Rfq {
        Rfq {
            ask_total_cost,
            bid_total_cost,
            cancel_reason,
            counterparties: None,
            creation_timestamp,
            filled_direction: None,
            filled_pct,
            label,
            last_update_timestamp,
            legs,
            mark_total_cost,
            max_total_cost,
            min_total_cost,
            partial_fill_step,
            rfq_id,
            status,
            subaccount_id,
            total_cost,
            valid_until,
            wallet,
        }
    }
}

