/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfqGetBestQuoteRequest {
    #[serde(rename = "direction", deserialize_with = "Option::deserialize")]
    pub direction: Option<serde_json::Value>,
    #[serde(rename = "legs", deserialize_with = "Option::deserialize")]
    pub legs: Option<serde_json::Value>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl RfqGetBestQuoteRequest {
    pub fn new(direction: Option<serde_json::Value>, legs: Option<serde_json::Value>, subaccount_id: i32) -> RfqGetBestQuoteRequest {
        RfqGetBestQuoteRequest {
            direction,
            legs,
            subaccount_id,
        }
    }
}

