/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfqPollResponse {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "rfqs")]
    pub rfqs: Vec<models::PublicRfq>,
}

impl RfqPollResponse {
    pub fn new(pagination: models::Pagination, rfqs: Vec<models::PublicRfq>) -> RfqPollResponse {
        RfqPollResponse {
            pagination,
            rfqs,
        }
    }
}

