/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfqGetBestQuoteResponse {
    #[serde(rename = "best_quote", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub best_quote: Option<Option<models::PublicQuote>>,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "down_liquidation_price", deserialize_with = "Option::deserialize")]
    pub down_liquidation_price: Option<bigdecimal::BigDecimal>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "estimated_fee")]
    pub estimated_fee: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "estimated_realized_pnl")]
    pub estimated_realized_pnl: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "estimated_realized_pnl_excl_fees")]
    pub estimated_realized_pnl_excl_fees: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "estimated_total_cost")]
    pub estimated_total_cost: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "filled_pct")]
    pub filled_pct: bigdecimal::BigDecimal,
    #[serde(rename = "invalid_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invalid_reason: Option<Option<String>>,
    #[serde(rename = "is_valid")]
    pub is_valid: bool,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "orderbook_total_cost", deserialize_with = "Option::deserialize")]
    pub orderbook_total_cost: Option<bigdecimal::BigDecimal>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "post_initial_margin")]
    pub post_initial_margin: bigdecimal::BigDecimal,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "post_liquidation_price", deserialize_with = "Option::deserialize")]
    pub post_liquidation_price: Option<bigdecimal::BigDecimal>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "pre_initial_margin")]
    pub pre_initial_margin: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "suggested_max_fee")]
    pub suggested_max_fee: bigdecimal::BigDecimal,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "up_liquidation_price", deserialize_with = "Option::deserialize")]
    pub up_liquidation_price: Option<bigdecimal::BigDecimal>,
}

impl RfqGetBestQuoteResponse {
    pub fn new(direction: models::Direction, down_liquidation_price: Option<bigdecimal::BigDecimal>, estimated_fee: bigdecimal::BigDecimal, estimated_realized_pnl: bigdecimal::BigDecimal, estimated_realized_pnl_excl_fees: bigdecimal::BigDecimal, estimated_total_cost: bigdecimal::BigDecimal, filled_pct: bigdecimal::BigDecimal, is_valid: bool, orderbook_total_cost: Option<bigdecimal::BigDecimal>, post_initial_margin: bigdecimal::BigDecimal, post_liquidation_price: Option<bigdecimal::BigDecimal>, pre_initial_margin: bigdecimal::BigDecimal, suggested_max_fee: bigdecimal::BigDecimal, up_liquidation_price: Option<bigdecimal::BigDecimal>) -> RfqGetBestQuoteResponse {
        RfqGetBestQuoteResponse {
            best_quote: None,
            direction,
            down_liquidation_price,
            estimated_fee,
            estimated_realized_pnl,
            estimated_realized_pnl_excl_fees,
            estimated_total_cost,
            filled_pct,
            invalid_reason: None,
            is_valid,
            orderbook_total_cost,
            post_initial_margin,
            post_liquidation_price,
            pre_initial_margin,
            suggested_max_fee,
            up_liquidation_price,
        }
    }
}

