/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RfqCancelReason {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "user_request")]
    UserRequest,
    #[serde(rename = "insufficient_margin")]
    InsufficientMargin,
    #[serde(rename = "signed_max_fee_too_low")]
    SignedMaxFeeTooLow,
    #[serde(rename = "mmp_trigger")]
    MmpTrigger,
    #[serde(rename = "cancel_on_disconnect")]
    CancelOnDisconnect,
    #[serde(rename = "session_key_deregistered")]
    SessionKeyDeregistered,
    #[serde(rename = "subaccount_withdrawn")]
    SubaccountWithdrawn,
    #[serde(rename = "rfq_no_longer_open")]
    RfqNoLongerOpen,
    #[serde(rename = "compliance")]
    Compliance,

}

impl std::fmt::Display for RfqCancelReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, ""),
            Self::UserRequest => write!(f, "user_request"),
            Self::InsufficientMargin => write!(f, "insufficient_margin"),
            Self::SignedMaxFeeTooLow => write!(f, "signed_max_fee_too_low"),
            Self::MmpTrigger => write!(f, "mmp_trigger"),
            Self::CancelOnDisconnect => write!(f, "cancel_on_disconnect"),
            Self::SessionKeyDeregistered => write!(f, "session_key_deregistered"),
            Self::SubaccountWithdrawn => write!(f, "subaccount_withdrawn"),
            Self::RfqNoLongerOpen => write!(f, "rfq_no_longer_open"),
            Self::Compliance => write!(f, "compliance"),
        }
    }
}

impl Default for RfqCancelReason {
    fn default() -> RfqCancelReason {
        Self::Empty
    }
}

