/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskUniverse : One risk universe: its display metadata, managers (each with what it lets you trade and deposit), and the Security Module absorbing the universe's losses. The universe-first mirror of `public/get_all_currencies` — pick a universe, pick a manager in it, and the `manager_id` is what you pass when depositing to a new subaccount.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskUniverse {
    /// Short description of the universe; null until set by the exchange.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The universe's managers (at most one Standard and one Portfolio), each with the instruments it risk-prices and the collaterals it accepts.
    #[serde(rename = "managers")]
    pub managers: Vec<models::RiskUniverseManager>,
    /// Display name (e.g. \"PRIME\"), always uppercase; null until set by the exchange.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    #[serde(rename = "security_module")]
    pub security_module: models::SecurityModuleDetails,
}

impl RiskUniverse {
    /// One risk universe: its display metadata, managers (each with what it lets you trade and deposit), and the Security Module absorbing the universe's losses. The universe-first mirror of `public/get_all_currencies` — pick a universe, pick a manager in it, and the `manager_id` is what you pass when depositing to a new subaccount.
    pub fn new(managers: Vec<models::RiskUniverseManager>, risk_universe_id: i32, security_module: models::SecurityModuleDetails) -> RiskUniverse {
        RiskUniverse {
            description: None,
            managers,
            name: None,
            risk_universe_id,
            security_module,
        }
    }
}

