/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskUniverseManager : A manager and what a subaccount created under it can trade and hold.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskUniverseManager {
    /// Assets this manager accepts as deposit collateral.
    #[serde(rename = "collaterals")]
    pub collaterals: Vec<models::ManagerCollateral>,
    /// Live derivative asset names tradeable under this manager, sorted (e.g. \"BTC-OPTION\", \"BTC-PERP\"). An option entry names the family — fetch its individual listings via `public/get_all_instruments`.
    #[serde(rename = "instruments")]
    pub instruments: Vec<String>,
    /// Pass this as `manager_id` when depositing to a new subaccount.
    #[serde(rename = "manager_id")]
    pub manager_id: i32,
    #[serde(rename = "margin_type")]
    pub margin_type: models::MarginType,
}

impl RiskUniverseManager {
    /// A manager and what a subaccount created under it can trade and hold.
    pub fn new(collaterals: Vec<models::ManagerCollateral>, instruments: Vec<String>, manager_id: i32, margin_type: models::MarginType) -> RiskUniverseManager {
        RiskUniverseManager {
            collaterals,
            instruments,
            manager_id,
            margin_type,
        }
    }
}

