/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecurityModuleDetails : The universe's Security Module: the subaccount whose funds absorb insolvent losses before any socialization within the universe.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityModuleDetails {
    /// EIP-55 checksummed address of the universe's cash asset.
    #[serde(rename = "cash_asset")]
    pub cash_asset: String,
    /// Currency of the cash asset (e.g. \"USDC\").
    #[serde(rename = "cash_currency")]
    pub cash_currency: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl SecurityModuleDetails {
    /// The universe's Security Module: the subaccount whose funds absorb insolvent losses before any socialization within the universe.
    pub fn new(cash_asset: String, cash_currency: String, subaccount_id: i32) -> SecurityModuleDetails {
        SecurityModuleDetails {
            cash_asset,
            cash_currency,
            subaccount_id,
        }
    }
}

