/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendQuoteRequest {
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee", skip_serializing_if = "Option::is_none")]
    pub extra_fee: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "legs")]
    pub legs: Vec<models::PricedLegParamsAndResponse>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "mmp", skip_serializing_if = "Option::is_none")]
    pub mmp: Option<bool>,
    #[serde(rename = "nonce")]
    pub nonce: i64,
    #[serde(rename = "referral_code", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<String>,
    /// UUID v4 string
    #[serde(rename = "rfq_id")]
    pub rfq_id: uuid::Uuid,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl SendQuoteRequest {
    pub fn new(direction: models::Direction, legs: Vec<models::PricedLegParamsAndResponse>, max_fee: bigdecimal::BigDecimal, nonce: i64, rfq_id: uuid::Uuid, signature: String, signature_expiry_sec: i64, signer: String, subaccount_id: i32) -> SendQuoteRequest {
        SendQuoteRequest {
            client: None,
            direction,
            extra_fee: None,
            label: None,
            legs,
            max_fee,
            mmp: None,
            nonce,
            referral_code: None,
            rfq_id,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

