/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendRfqRequest {
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    #[serde(rename = "counterparties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub counterparties: Option<Option<Vec<String>>>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee", skip_serializing_if = "Option::is_none")]
    pub extra_fee: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "legs", deserialize_with = "Option::deserialize")]
    pub legs: Option<serde_json::Value>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "max_total_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_total_cost: Option<Option<bigdecimal::BigDecimal>>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "min_total_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_total_cost: Option<Option<bigdecimal::BigDecimal>>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "partial_fill_step", skip_serializing_if = "Option::is_none")]
    pub partial_fill_step: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "referral_code", skip_serializing_if = "Option::is_none")]
    pub referral_code: Option<String>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl SendRfqRequest {
    pub fn new(legs: Option<serde_json::Value>, subaccount_id: i32) -> SendRfqRequest {
        SendRfqRequest {
            client: None,
            counterparties: None,
            extra_fee: None,
            label: None,
            legs,
            max_total_cost: None,
            min_total_cost: None,
            partial_fill_step: None,
            referral_code: None,
            subaccount_id,
        }
    }
}

