/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionKey {
    #[serde(rename = "expiry_sec")]
    pub expiry_sec: i32,
    #[serde(rename = "ip_whitelist")]
    pub ip_whitelist: Vec<String>,
    #[serde(rename = "label")]
    pub label: String,
    /// Off-chain scopes (read-tier capabilities).
    #[serde(rename = "offchain_scopes")]
    pub offchain_scopes: Vec<String>,
    /// Protocol-level (on-chain authority) scopes.
    #[serde(rename = "protocol_scopes")]
    pub protocol_scopes: Vec<String>,
    #[serde(rename = "public_session_key")]
    pub public_session_key: String,
    #[serde(rename = "registered_sec")]
    pub registered_sec: i32,
    /// Subaccounts this key may act on. An empty stored value means \"all subaccounts\" and is expanded to the wallet's current subaccount list.
    #[serde(rename = "subaccount_ids")]
    pub subaccount_ids: Vec<i32>,
}

impl SessionKey {
    pub fn new(expiry_sec: i32, ip_whitelist: Vec<String>, label: String, offchain_scopes: Vec<String>, protocol_scopes: Vec<String>, public_session_key: String, registered_sec: i32, subaccount_ids: Vec<i32>) -> SessionKey {
        SessionKey {
            expiry_sec,
            ip_whitelist,
            label,
            offchain_scopes,
            protocol_scopes,
            public_session_key,
            registered_sec,
            subaccount_ids,
        }
    }
}

