/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetMmpConfigResponse : Echoes the inbound params back: decimal-string limits, ms intervals.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetMmpConfigResponse {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "mmp_amount_limit")]
    pub mmp_amount_limit: String,
    #[serde(rename = "mmp_delta_limit")]
    pub mmp_delta_limit: String,
    #[serde(rename = "mmp_frozen_time")]
    pub mmp_frozen_time: i32,
    #[serde(rename = "mmp_interval")]
    pub mmp_interval: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl SetMmpConfigResponse {
    /// Echoes the inbound params back: decimal-string limits, ms intervals.
    pub fn new(currency: String, mmp_amount_limit: String, mmp_delta_limit: String, mmp_frozen_time: i32, mmp_interval: i32, subaccount_id: i32) -> SetMmpConfigResponse {
        SetMmpConfigResponse {
            currency,
            mmp_amount_limit,
            mmp_delta_limit,
            mmp_frozen_time,
            mmp_interval,
            subaccount_id,
        }
    }
}

