/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetMmpConfigRequest : `mmp_interval` and `mmp_frozen_time` are specified in milliseconds (rounded down to the nearest whole second).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetMmpConfigRequest {
    #[serde(rename = "currency")]
    pub currency: String,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "mmp_amount_limit", skip_serializing_if = "Option::is_none")]
    pub mmp_amount_limit: Option<bigdecimal::BigDecimal>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "mmp_delta_limit", skip_serializing_if = "Option::is_none")]
    pub mmp_delta_limit: Option<bigdecimal::BigDecimal>,
    #[serde(rename = "mmp_frozen_time")]
    pub mmp_frozen_time: i32,
    #[serde(rename = "mmp_interval")]
    pub mmp_interval: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
}

impl SetMmpConfigRequest {
    /// `mmp_interval` and `mmp_frozen_time` are specified in milliseconds (rounded down to the nearest whole second).
    pub fn new(currency: String, mmp_frozen_time: i32, mmp_interval: i32, subaccount_id: i32) -> SetMmpConfigRequest {
        SetMmpConfigRequest {
            currency,
            mmp_amount_limit: None,
            mmp_delta_limit: None,
            mmp_frozen_time,
            mmp_interval,
            subaccount_id,
        }
    }
}

