/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettledTrade : A settled trade returned by `public/get_trade_history`. Anonymized: no `order_id` or `label`. `wallet` is included since settled trades are visible on-chain.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettledTrade {
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "expected_rebate")]
    pub expected_rebate: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee")]
    pub extra_fee: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "index_price")]
    pub index_price: bigdecimal::BigDecimal,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "liquidity_role")]
    pub liquidity_role: models::LiquidityRole,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "mark_price")]
    pub mark_price: bigdecimal::BigDecimal,
    /// Optional UUID v4 string
    #[serde(rename = "quote_id", deserialize_with = "Option::deserialize")]
    pub quote_id: Option<uuid::Uuid>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "realized_pnl_excl_fees")]
    pub realized_pnl_excl_fees: bigdecimal::BigDecimal,
    /// Optional UUID v4 string
    #[serde(rename = "rfq_id", deserialize_with = "Option::deserialize")]
    pub rfq_id: Option<uuid::Uuid>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_amount")]
    pub trade_amount: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_fee")]
    pub trade_fee: bigdecimal::BigDecimal,
    #[serde(rename = "trade_id")]
    pub trade_id: String,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_price")]
    pub trade_price: bigdecimal::BigDecimal,
    #[serde(rename = "tx_hash")]
    pub tx_hash: String,
    #[serde(rename = "tx_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_status: Option<Option<models::BatchStatus>>,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl SettledTrade {
    /// A settled trade returned by `public/get_trade_history`. Anonymized: no `order_id` or `label`. `wallet` is included since settled trades are visible on-chain.
    pub fn new(direction: models::Direction, expected_rebate: bigdecimal::BigDecimal, extra_fee: bigdecimal::BigDecimal, index_price: bigdecimal::BigDecimal, instrument_name: String, liquidity_role: models::LiquidityRole, mark_price: bigdecimal::BigDecimal, quote_id: Option<uuid::Uuid>, realized_pnl: bigdecimal::BigDecimal, realized_pnl_excl_fees: bigdecimal::BigDecimal, rfq_id: Option<uuid::Uuid>, subaccount_id: i64, timestamp: i64, trade_amount: bigdecimal::BigDecimal, trade_fee: bigdecimal::BigDecimal, trade_id: String, trade_price: bigdecimal::BigDecimal, tx_hash: String, wallet: String) -> SettledTrade {
        SettledTrade {
            direction,
            expected_rebate,
            extra_fee,
            index_price,
            instrument_name,
            liquidity_role,
            mark_price,
            quote_id,
            realized_pnl,
            realized_pnl_excl_fees,
            rfq_id,
            subaccount_id,
            timestamp,
            trade_amount,
            trade_fee,
            trade_id,
            trade_price,
            tx_hash,
            tx_status: None,
            wallet,
        }
    }
}

