/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignedAction : An Action bundled with its ECDSA signature (65 bytes: r||s||v).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignedAction {
    /// The signed action envelope.
    #[serde(rename = "action")]
    pub action: models::Action,
    /// 65-byte ECDSA signature (r||s||v).
    #[serde(rename = "signature")]
    pub signature: Vec<i32>,
}

impl SignedAction {
    /// An Action bundled with its ECDSA signature (65 bytes: r||s||v).
    pub fn new(action: models::Action, signature: Vec<i32>) -> SignedAction {
        SignedAction {
            action,
            signature,
        }
    }
}

