/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignedTransferQuoteRequest : Action info that needs to be signed by quoter or RFQ executor for a transfer. The quoter signs the legs hash + max fee; the executor signs the same legs hash + their own max fee.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignedTransferQuoteRequest {
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    #[serde(rename = "legs")]
    pub legs: Vec<models::PricedLegParamsAndResponse>,
    /// Maximum fee the signer authorises, in USD, as a decimal string (e.g. `\"1.5\"`) or a JSON number.
    #[serde(rename = "max_fee")]
    pub max_fee: bigdecimal::BigDecimal,
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i64,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "signer")]
    pub signer: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
}

impl SignedTransferQuoteRequest {
    /// Action info that needs to be signed by quoter or RFQ executor for a transfer. The quoter signs the legs hash + max fee; the executor signs the same legs hash + their own max fee.
    pub fn new(direction: models::Direction, legs: Vec<models::PricedLegParamsAndResponse>, max_fee: bigdecimal::BigDecimal, nonce: String, signature: String, signature_expiry_sec: i64, signer: String, subaccount_id: i64) -> SignedTransferQuoteRequest {
        SignedTransferQuoteRequest {
            direction,
            legs,
            max_fee,
            nonce,
            signature,
            signature_expiry_sec,
            signer,
            subaccount_id,
        }
    }
}

