/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotFeedDataResponse {
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deadline")]
    pub deadline: i32,
    #[serde(rename = "feed_source_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_source_type: Option<Option<String>>,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "signatures")]
    pub signatures: models::OracleSignatureDataResponse,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl SpotFeedDataResponse {
    pub fn new(confidence: String, currency: String, deadline: i32, price: String, signatures: models::OracleSignatureDataResponse, timestamp: i32) -> SpotFeedDataResponse {
        SpotFeedDataResponse {
            confidence,
            currency,
            deadline,
            feed_source_type: None,
            price,
            signatures,
            timestamp,
        }
    }
}

