/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpotAssetEntry : A spot asset and its per-universe risk: collateral discounts, lending, OI.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotAssetEntry {
    /// EIP-55 checksummed protocol asset address.
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "erc20")]
    pub erc20: models::Erc20Details,
    #[serde(rename = "min_deposit_usd")]
    pub min_deposit_usd: String,
    /// Registered asset name (e.g. \"USDC\", \"USDC-NL\").
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "universes")]
    pub universes: Vec<models::SpotUniverse>,
}

impl SpotAssetEntry {
    /// A spot asset and its per-universe risk: collateral discounts, lending, OI.
    pub fn new(address: String, erc20: models::Erc20Details, min_deposit_usd: String, name: String, universes: Vec<models::SpotUniverse>) -> SpotAssetEntry {
        SpotAssetEntry {
            address,
            erc20,
            min_deposit_usd,
            name,
            universes,
        }
    }
}

