/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpotUniverse : Risk details for a single `(spot_asset, universe)` pair.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotUniverse {
    #[serde(rename = "lending", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lending: Option<Option<models::LendingDetails>>,
    /// Spot supply OI cap + current supply (for a lending asset, the current supply is the pool's total supplied collateral).
    #[serde(rename = "oi")]
    pub oi: models::OpenInterestStats,
    /// PMRM2 collateral haircut (\"0\" if not collateralized).
    #[serde(rename = "pm2_im_discount")]
    pub pm2_im_discount: String,
    #[serde(rename = "pm2_mm_discount")]
    pub pm2_mm_discount: String,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    /// SRM collateral discount (cash asset \"1\"; non-collateral \"0\").
    #[serde(rename = "srm_im_discount")]
    pub srm_im_discount: String,
    #[serde(rename = "srm_mm_discount")]
    pub srm_mm_discount: String,
}

impl SpotUniverse {
    /// Risk details for a single `(spot_asset, universe)` pair.
    pub fn new(oi: models::OpenInterestStats, pm2_im_discount: String, pm2_mm_discount: String, risk_universe_id: i32, srm_im_discount: String, srm_mm_discount: String) -> SpotUniverse {
        SpotUniverse {
            lending: None,
            oi,
            pm2_im_discount,
            pm2_mm_discount,
            risk_universe_id,
            srm_im_discount,
            srm_mm_discount,
        }
    }
}

