/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subaccount {
    #[serde(rename = "collaterals")]
    pub collaterals: Vec<models::Collateral>,
    #[serde(rename = "collaterals_initial_margin")]
    pub collaterals_initial_margin: String,
    #[serde(rename = "collaterals_maintenance_margin")]
    pub collaterals_maintenance_margin: String,
    #[serde(rename = "collaterals_value")]
    pub collaterals_value: String,
    #[serde(rename = "currency")]
    pub currency: Vec<String>,
    /// `true` if this subaccount's portfolio could not be loaded; such subaccounts are returned as placeholders by `get_all_portfolios`.
    #[serde(rename = "failed_to_fetch")]
    pub failed_to_fetch: bool,
    #[serde(rename = "initial_margin")]
    pub initial_margin: String,
    #[serde(rename = "is_under_liquidation")]
    pub is_under_liquidation: bool,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "maintenance_margin")]
    pub maintenance_margin: String,
    #[serde(rename = "manager_id")]
    pub manager_id: i32,
    #[serde(rename = "margin_type")]
    pub margin_type: String,
    #[serde(rename = "open_orders")]
    pub open_orders: Vec<models::Order>,
    #[serde(rename = "open_orders_margin")]
    pub open_orders_margin: String,
    #[serde(rename = "positions")]
    pub positions: Vec<models::Position>,
    #[serde(rename = "positions_initial_margin")]
    pub positions_initial_margin: String,
    #[serde(rename = "positions_maintenance_margin")]
    pub positions_maintenance_margin: String,
    #[serde(rename = "positions_value")]
    pub positions_value: String,
    #[serde(rename = "projected_margin_change")]
    pub projected_margin_change: String,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "subaccount_value")]
    pub subaccount_value: String,
    #[serde(rename = "vault_deposit_holds")]
    pub vault_deposit_holds: Vec<models::VaultDepositHold>,
}

impl Subaccount {
    pub fn new(collaterals: Vec<models::Collateral>, collaterals_initial_margin: String, collaterals_maintenance_margin: String, collaterals_value: String, currency: Vec<String>, failed_to_fetch: bool, initial_margin: String, is_under_liquidation: bool, label: String, maintenance_margin: String, manager_id: i32, margin_type: String, open_orders: Vec<models::Order>, open_orders_margin: String, positions: Vec<models::Position>, positions_initial_margin: String, positions_maintenance_margin: String, positions_value: String, projected_margin_change: String, risk_universe_id: i32, subaccount_id: i32, subaccount_value: String, vault_deposit_holds: Vec<models::VaultDepositHold>) -> Subaccount {
        Subaccount {
            collaterals,
            collaterals_initial_margin,
            collaterals_maintenance_margin,
            collaterals_value,
            currency,
            failed_to_fetch,
            initial_margin,
            is_under_liquidation,
            label,
            maintenance_margin,
            manager_id,
            margin_type,
            open_orders,
            open_orders_margin,
            positions,
            positions_initial_margin,
            positions_maintenance_margin,
            positions_value,
            projected_margin_change,
            risk_universe_id,
            subaccount_id,
            subaccount_value,
            vault_deposit_holds,
        }
    }
}

