/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickerSlimSnapshot {
    /// Amount of contracts / tokens available at the best ask price.
    #[serde(rename = "A")]
    pub a: String,
    /// Amount of contracts / tokens available at the best bid price.
    #[serde(rename = "B")]
    pub b: String,
    /// Index price.
    #[serde(rename = "I")]
    pub i: String,
    /// Mark price.
    #[serde(rename = "M")]
    pub m: String,
    /// Best ask price.
    #[serde(rename = "a")]
    pub a: String,
    /// Best bid price.
    #[serde(rename = "b")]
    pub b: String,
    /// Current hourly funding rate (perpetuals only; `null` otherwise).
    #[serde(rename = "f", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub f: Option<Option<String>>,
    /// Maximum price at which an aggressive buyer can be matched. Any portion of a market order that would execute above this price is cancelled. A limit buy order with limit price above this value is treated as post only (i.e. it is rejected if it would cross any existing resting order).
    #[serde(rename = "maxp")]
    pub maxp: String,
    /// Minimum price at which an aggressive seller can be matched. Any portion of a market order that would execute below this price is cancelled. A limit sell order with limit price below this value is treated as post only (i.e. it is rejected if it would cross any existing resting order).
    #[serde(rename = "minp")]
    pub minp: String,
    #[serde(rename = "option_pricing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_pricing: Option<Option<models::OptionPricing>>,
    /// Trailing 24-hour trading statistics.
    #[serde(rename = "stats")]
    pub stats: models::DailyTradingStatistics,
    /// Snapshot creation timestamp, in milliseconds since the Unix epoch.
    #[serde(rename = "t")]
    pub t: i64,
}

impl TickerSlimSnapshot {
    pub fn new(a: String, b: String, i: String, m: String, a: String, b: String, maxp: String, minp: String, stats: models::DailyTradingStatistics, t: i64) -> TickerSlimSnapshot {
        TickerSlimSnapshot {
            a,
            b,
            i,
            m,
            a,
            b,
            f: None,
            maxp,
            minp,
            option_pricing: None,
            stats,
            t,
        }
    }
}

