/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeInForce {
    #[serde(rename = "gtc")]
    Gtc,
    #[serde(rename = "post_only")]
    PostOnly,
    #[serde(rename = "fok")]
    Fok,
    #[serde(rename = "ioc")]
    Ioc,

}

impl std::fmt::Display for TimeInForce {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Gtc => write!(f, "gtc"),
            Self::PostOnly => write!(f, "post_only"),
            Self::Fok => write!(f, "fok"),
            Self::Ioc => write!(f, "ioc"),
        }
    }
}

impl Default for TimeInForce {
    fn default() -> TimeInForce {
        Self::Gtc
    }
}

