/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Trade : Info that the user expects to get delivered when requesting trade info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Trade {
    #[serde(rename = "direction")]
    pub direction: models::Direction,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "expected_rebate")]
    pub expected_rebate: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "extra_fee")]
    pub extra_fee: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "index_price")]
    pub index_price: bigdecimal::BigDecimal,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "is_transfer")]
    pub is_transfer: bool,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "liquidity_role")]
    pub liquidity_role: models::LiquidityRole,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "mark_price")]
    pub mark_price: bigdecimal::BigDecimal,
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "order_id")]
    pub order_id: String,
    /// Optional UUID v4 string
    #[serde(rename = "quote_id", deserialize_with = "Option::deserialize")]
    pub quote_id: Option<uuid::Uuid>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "realized_pnl")]
    pub realized_pnl: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "realized_pnl_excl_fees")]
    pub realized_pnl_excl_fees: bigdecimal::BigDecimal,
    /// Optional UUID v4 string
    #[serde(rename = "rfq_id", deserialize_with = "Option::deserialize")]
    pub rfq_id: Option<uuid::Uuid>,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i64,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_amount")]
    pub trade_amount: bigdecimal::BigDecimal,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_fee")]
    pub trade_fee: bigdecimal::BigDecimal,
    #[serde(rename = "trade_id")]
    pub trade_id: String,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "trade_price")]
    pub trade_price: bigdecimal::BigDecimal,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
    #[serde(rename = "tx_status")]
    pub tx_status: models::TxStatus,
}

impl Trade {
    /// Info that the user expects to get delivered when requesting trade info.
    pub fn new(direction: models::Direction, expected_rebate: bigdecimal::BigDecimal, extra_fee: bigdecimal::BigDecimal, index_price: bigdecimal::BigDecimal, instrument_name: String, is_transfer: bool, liquidity_role: models::LiquidityRole, mark_price: bigdecimal::BigDecimal, op_uuid: String, order_id: String, quote_id: Option<uuid::Uuid>, realized_pnl: bigdecimal::BigDecimal, realized_pnl_excl_fees: bigdecimal::BigDecimal, rfq_id: Option<uuid::Uuid>, subaccount_id: i64, timestamp: i64, trade_amount: bigdecimal::BigDecimal, trade_fee: bigdecimal::BigDecimal, trade_id: String, trade_price: bigdecimal::BigDecimal, tx_status: models::TxStatus) -> Trade {
        Trade {
            direction,
            expected_rebate,
            extra_fee,
            index_price,
            instrument_name,
            is_transfer,
            label: None,
            liquidity_role,
            mark_price,
            op_uuid,
            order_id,
            quote_id,
            realized_pnl,
            realized_pnl_excl_fees,
            rfq_id,
            subaccount_id,
            timestamp,
            trade_amount,
            trade_fee,
            trade_id,
            trade_price,
            tx_hash: None,
            tx_status,
        }
    }
}

