/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TradingviewCandle : Single trades OHLCV candle in `public/get_tradingview_chart_data`. `timestamp` and `timestamp_bucket` are the bucket start in UTC seconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradingviewCandle {
    #[serde(rename = "close_price")]
    pub close_price: String,
    #[serde(rename = "high_price")]
    pub high_price: String,
    #[serde(rename = "low_price")]
    pub low_price: String,
    #[serde(rename = "open_price")]
    pub open_price: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "timestamp_bucket")]
    pub timestamp_bucket: i64,
    #[serde(rename = "volume_contracts")]
    pub volume_contracts: String,
    #[serde(rename = "volume_usd")]
    pub volume_usd: String,
}

impl TradingviewCandle {
    /// Single trades OHLCV candle in `public/get_tradingview_chart_data`. `timestamp` and `timestamp_bucket` are the bucket start in UTC seconds.
    pub fn new(close_price: String, high_price: String, low_price: String, open_price: String, timestamp: i64, timestamp_bucket: i64, volume_contracts: String, volume_usd: String) -> TradingviewCandle {
        TradingviewCandle {
            close_price,
            high_price,
            low_price,
            open_price,
            timestamp,
            timestamp_bucket,
            volume_contracts,
            volume_usd,
        }
    }
}

