/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferEntry : `amount` and `fee` are decimal strings (e.g. `\"1.1\"`). `is_outgoing` marks the caller's side; on the sender's row `amount` is the gross debited and `fee` the in-kind fee, on the receiver's row `amount` is the net credited and `fee` is 0. `operation_id`/`batch_uuid` are stable uuids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferEntry {
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "batch_status")]
    pub batch_status: models::BatchStatus,
    #[serde(rename = "batch_uuid")]
    pub batch_uuid: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fee")]
    pub fee: bigdecimal::BigDecimal,
    #[serde(rename = "from_subaccount_id")]
    pub from_subaccount_id: i32,
    #[serde(rename = "from_wallet")]
    pub from_wallet: String,
    #[serde(rename = "is_outgoing")]
    pub is_outgoing: bool,
    #[serde(rename = "operation_id")]
    pub operation_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "to_subaccount_id")]
    pub to_subaccount_id: i32,
    #[serde(rename = "to_wallet")]
    pub to_wallet: String,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
}

impl TransferEntry {
    /// `amount` and `fee` are decimal strings (e.g. `\"1.1\"`). `is_outgoing` marks the caller's side; on the sender's row `amount` is the gross debited and `fee` the in-kind fee, on the receiver's row `amount` is the net credited and `fee` is 0. `operation_id`/`batch_uuid` are stable uuids.
    pub fn new(amount: bigdecimal::BigDecimal, asset: String, batch_status: models::BatchStatus, batch_uuid: String, fee: bigdecimal::BigDecimal, from_subaccount_id: i32, from_wallet: String, is_outgoing: bool, operation_id: String, timestamp: i32, to_subaccount_id: i32, to_wallet: String) -> TransferEntry {
        TransferEntry {
            amount,
            asset,
            batch_status,
            batch_uuid,
            fee,
            from_subaccount_id,
            from_wallet,
            is_outgoing,
            operation_id,
            timestamp,
            to_subaccount_id,
            to_wallet,
            tx_hash: None,
        }
    }
}

