/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferPositionsRequest : Params for `private/transfer_positions`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferPositionsRequest {
    #[serde(rename = "maker_params")]
    pub maker_params: models::SignedTransferQuoteRequest,
    #[serde(rename = "taker_params")]
    pub taker_params: models::SignedTransferQuoteRequest,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl TransferPositionsRequest {
    /// Params for `private/transfer_positions`.
    pub fn new(maker_params: models::SignedTransferQuoteRequest, taker_params: models::SignedTransferQuoteRequest, wallet: String) -> TransferPositionsRequest {
        TransferPositionsRequest {
            maker_params,
            taker_params,
            wallet,
        }
    }
}

