/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferPositionsResponse : Result for `private/transfer_positions`. Carries the synthesized maker and taker quote payloads so clients see a response shape parallel to `private/execute_quote`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferPositionsResponse {
    #[serde(rename = "maker_quote")]
    pub maker_quote: models::Quote,
    #[serde(rename = "taker_quote")]
    pub taker_quote: models::Quote,
}

impl TransferPositionsResponse {
    /// Result for `private/transfer_positions`. Carries the synthesized maker and taker quote payloads so clients see a response shape parallel to `private/execute_quote`.
    pub fn new(maker_quote: models::Quote, taker_quote: models::Quote) -> TransferPositionsResponse {
        TransferPositionsResponse {
            maker_quote,
            taker_quote,
        }
    }
}

