/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerPriceType {
    #[serde(rename = "mark")]
    Mark,
    #[serde(rename = "index")]
    Index,

}

impl std::fmt::Display for TriggerPriceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mark => write!(f, "mark"),
            Self::Index => write!(f, "index"),
        }
    }
}

impl Default for TriggerPriceType {
    fn default() -> TriggerPriceType {
        Self::Mark
    }
}

