/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerType {
    #[serde(rename = "stoploss")]
    Stoploss,
    #[serde(rename = "takeprofit")]
    Takeprofit,

}

impl std::fmt::Display for TriggerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stoploss => write!(f, "stoploss"),
            Self::Takeprofit => write!(f, "takeprofit"),
        }
    }
}

impl Default for TriggerType {
    fn default() -> TriggerType {
        Self::Stoploss
    }
}

