/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TxStatus {
    String(String),
    /// Applied off-chain; not yet included in an on-chain settlement batch.
    String(String),
    /// Included in a settlement batch and executing.
    String(String),
    /// Settlement proof in progress.
    String(String),
    /// Settlement transaction broadcast on-chain; awaiting confirmation.
    String(String),
}

impl Default for TxStatus {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

