/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UniverseManagers : The managers risk-pricing a currency within one universe.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UniverseManagers {
    /// PMRM2 manager id risking this currency in the universe.
    #[serde(rename = "pm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pm: Option<Option<i32>>,
    #[serde(rename = "risk_universe_id")]
    pub risk_universe_id: i32,
    /// Display name of the universe (uppercase, e.g. \"PRIME\"); absent until set by the exchange.
    #[serde(rename = "risk_universe_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_universe_name: Option<Option<String>>,
    /// SRM manager id risking this currency in the universe.
    #[serde(rename = "sm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sm: Option<Option<i32>>,
}

impl UniverseManagers {
    /// The managers risk-pricing a currency within one universe.
    pub fn new(risk_universe_id: i32) -> UniverseManagers {
        UniverseManagers {
            pm: None,
            risk_universe_id,
            risk_universe_name: None,
            sm: None,
        }
    }
}

