/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWhitelistedRecipientsRequest {
    /// Recipient wallet addresses to add to the whitelist.
    #[serde(rename = "add")]
    pub add: Vec<String>,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// Recipient wallet addresses to remove from the whitelist.
    #[serde(rename = "remove")]
    pub remove: Vec<String>,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signature_expiry_sec")]
    pub signature_expiry_sec: i32,
    #[serde(rename = "signer")]
    pub signer: String,
    /// Wallet whose whitelist is being updated; becomes the action owner.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl UpdateWhitelistedRecipientsRequest {
    pub fn new(add: Vec<String>, nonce: i32, remove: Vec<String>, signature: String, signature_expiry_sec: i32, signer: String, wallet: String) -> UpdateWhitelistedRecipientsRequest {
        UpdateWhitelistedRecipientsRequest {
            add,
            nonce,
            remove,
            signature,
            signature_expiry_sec,
            signer,
            wallet,
        }
    }
}

