/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateVaultInfoRequest {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Advisory mark-to-market cap in USD, as a decimal string (e.g. `\"1000\"`).
    #[serde(rename = "mtm_cap", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mtm_cap: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The vault's subaccount ID; the caller must be the vault's curator.
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "whitelist_only", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub whitelist_only: Option<Option<bool>>,
}

impl UpdateVaultInfoRequest {
    pub fn new(subaccount_id: i32) -> UpdateVaultInfoRequest {
        UpdateVaultInfoRequest {
            description: None,
            mtm_cap: None,
            name: None,
            subaccount_id,
            whitelist_only: None,
        }
    }
}

