/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultPerformancePointResponse : One point in a vault's performance series. `ts` is the bucket time (epoch millis); each monetary value is the bucket's last sample as a decimal string. Live prices are nullable (a vault that couldn't be priced).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultPerformancePointResponse {
    /// Optional non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "benchmark_price", deserialize_with = "Option::deserialize")]
    pub benchmark_price: Option<bigdecimal::BigDecimal>,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "curator_shares")]
    pub curator_shares: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "global_hwm")]
    pub global_hwm: bigdecimal::BigDecimal,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "nav", deserialize_with = "Option::deserialize")]
    pub nav: Option<bigdecimal::BigDecimal>,
    /// Optional decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "nav_benchmark", deserialize_with = "Option::deserialize")]
    pub nav_benchmark: Option<bigdecimal::BigDecimal>,
    /// Decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "share_price")]
    pub share_price: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "total_shares")]
    pub total_shares: bigdecimal::BigDecimal,
    #[serde(rename = "ts")]
    pub ts: i64,
}

impl VaultPerformancePointResponse {
    /// One point in a vault's performance series. `ts` is the bucket time (epoch millis); each monetary value is the bucket's last sample as a decimal string. Live prices are nullable (a vault that couldn't be priced).
    pub fn new(benchmark_price: Option<bigdecimal::BigDecimal>, curator_shares: bigdecimal::BigDecimal, global_hwm: bigdecimal::BigDecimal, nav: Option<bigdecimal::BigDecimal>, nav_benchmark: Option<bigdecimal::BigDecimal>, share_price: bigdecimal::BigDecimal, total_shares: bigdecimal::BigDecimal, ts: i64) -> VaultPerformancePointResponse {
        VaultPerformancePointResponse {
            benchmark_price,
            curator_shares,
            global_hwm,
            nav,
            nav_benchmark,
            share_price,
            total_shares,
            ts,
        }
    }
}

