/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultActionResponse : A vault action as surfaced to the requesting user. Monetary fields (amounts, prices, share price) are decimal strings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultActionResponse {
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "after_shares")]
    pub after_shares: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "before_shares")]
    pub before_shares: bigdecimal::BigDecimal,
    /// Timestamp the request was created (ms).
    #[serde(rename = "creation_timestamp_ms")]
    pub creation_timestamp_ms: i64,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "entry_price")]
    pub entry_price: bigdecimal::BigDecimal,
    #[serde(rename = "error_reason")]
    pub error_reason: String,
    /// Timestamp of this event (ms).
    #[serde(rename = "event_ts")]
    pub event_ts: i64,
    /// \"vault_deposit\" | \"vault_withdraw\" | \"vault_force_withdraw\" | \"vault_cancel\".
    #[serde(rename = "event_type")]
    pub event_type: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "exit_price")]
    pub exit_price: bigdecimal::BigDecimal,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
    #[serde(rename = "operation_uuid")]
    pub operation_uuid: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "share_price")]
    pub share_price: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "shares_delta")]
    pub shares_delta: bigdecimal::BigDecimal,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "shares_requested")]
    pub shares_requested: bigdecimal::BigDecimal,
    /// While the action is in the queue, can be one of the following: \"enqueued\" | \"sequencer_applied\" | \"user_cancel\" | \"curator_reject\" | \"protocol_reject\" | \"expired\".  Once action is applied in the protocol, the status takes on `BatchStatus` values: \"Batching\" | \"Executing\" | \"Proving\" | \"Settling\" | \"Settled\" or an error.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "user_action_hash")]
    pub user_action_hash: String,
    #[serde(rename = "vault_nonce")]
    pub vault_nonce: String,
    #[serde(rename = "vault_subaccount_id")]
    pub vault_subaccount_id: i32,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl VaultActionResponse {
    /// A vault action as surfaced to the requesting user. Monetary fields (amounts, prices, share price) are decimal strings.
    pub fn new(after_shares: bigdecimal::BigDecimal, amount: bigdecimal::BigDecimal, before_shares: bigdecimal::BigDecimal, creation_timestamp_ms: i64, entry_price: bigdecimal::BigDecimal, error_reason: String, event_ts: i64, event_type: String, exit_price: bigdecimal::BigDecimal, operation_id: i32, operation_uuid: String, share_price: bigdecimal::BigDecimal, shares_delta: bigdecimal::BigDecimal, shares_requested: bigdecimal::BigDecimal, status: String, user_action_hash: String, vault_nonce: String, vault_subaccount_id: i32, wallet: String) -> VaultActionResponse {
        VaultActionResponse {
            after_shares,
            amount,
            before_shares,
            creation_timestamp_ms,
            entry_price,
            error_reason,
            event_ts,
            event_type,
            exit_price,
            operation_id,
            operation_uuid,
            share_price,
            shares_delta,
            shares_requested,
            status,
            user_action_hash,
            vault_nonce,
            vault_subaccount_id,
            wallet,
        }
    }
}

