/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultSettleResponse : Returned by `mint_vault_shares` / `burn_vault_shares`: identifiers to track the on-chain `MintShares` / `BurnShares` settlement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultSettleResponse {
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
}

impl VaultSettleResponse {
    /// Returned by `mint_vault_shares` / `burn_vault_shares`: identifiers to track the on-chain `MintShares` / `BurnShares` settlement.
    pub fn new(op_uuid: String, operation_id: i32) -> VaultSettleResponse {
        VaultSettleResponse {
            op_uuid,
            operation_id,
        }
    }
}

