/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultSharesResponse : Returned by `get_vault_shares`: one entry per vault the wallet holds shares in.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultSharesResponse {
    #[serde(rename = "vaults")]
    pub vaults: Vec<models::VaultShareEntryResponse>,
}

impl VaultSharesResponse {
    /// Returned by `get_vault_shares`: one entry per vault the wallet holds shares in.
    pub fn new(vaults: Vec<models::VaultShareEntryResponse>) -> VaultSharesResponse {
        VaultSharesResponse {
            vaults,
        }
    }
}

