/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultCreateResponse : Returned by `create_vault`: identifiers to track the on-chain `CreateVault` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultCreateResponse {
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
}

impl VaultCreateResponse {
    /// Returned by `create_vault`: identifiers to track the on-chain `CreateVault` operation.
    pub fn new(op_uuid: String, operation_id: i32) -> VaultCreateResponse {
        VaultCreateResponse {
            op_uuid,
            operation_id,
        }
    }
}

