/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultRequestResponse : One queued deposit/withdraw request as surfaced to the curator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultRequestResponse {
    #[serde(rename = "creation_timestamp_ms")]
    pub creation_timestamp_ms: i32,
    #[serde(rename = "id")]
    pub id: models::VaultRequestId,
    /// The user's signed deposit/withdraw envelope; the curator pairs their `MintShares`/`BurnShares` approval against it.
    #[serde(rename = "signed_action")]
    pub signed_action: models::SignedAction,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    /// 0x-prefixed hex of the 32-byte user-action hash the curator commits to.
    #[serde(rename = "user_action_hash")]
    pub user_action_hash: String,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl VaultRequestResponse {
    /// One queued deposit/withdraw request as surfaced to the curator.
    pub fn new(creation_timestamp_ms: i32, id: models::VaultRequestId, signed_action: models::SignedAction, subaccount_id: i32, user_action_hash: String, wallet: String) -> VaultRequestResponse {
        VaultRequestResponse {
            creation_timestamp_ms,
            id,
            signed_action,
            subaccount_id,
            user_action_hash,
            wallet,
        }
    }
}

