/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultCancelResponse : Returned by `cancel_all_vault_requests`: identifiers to track the on-chain `VaultCancel` operation plus the ids of the wallet's pending requests that were cancelled.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultCancelResponse {
    #[serde(rename = "cancelled_request_ids")]
    pub cancelled_request_ids: Vec<models::VaultRequestId>,
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
}

impl VaultCancelResponse {
    /// Returned by `cancel_all_vault_requests`: identifiers to track the on-chain `VaultCancel` operation plus the ids of the wallet's pending requests that were cancelled.
    pub fn new(cancelled_request_ids: Vec<models::VaultRequestId>, op_uuid: String, operation_id: i32) -> VaultCancelResponse {
        VaultCancelResponse {
            cancelled_request_ids,
            op_uuid,
            operation_id,
        }
    }
}

