/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultIdsResponse : Returned by `get_curated_vaults` / `get_shareholder_vaults`: the vault subaccount ids the caller curates / holds shares in.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultIdsResponse {
    #[serde(rename = "subaccount_ids")]
    pub subaccount_ids: Vec<i32>,
}

impl VaultIdsResponse {
    /// Returned by `get_curated_vaults` / `get_shareholder_vaults`: the vault subaccount ids the caller curates / holds shares in.
    pub fn new(subaccount_ids: Vec<i32>) -> VaultIdsResponse {
        VaultIdsResponse {
            subaccount_ids,
        }
    }
}

