/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultDepositHold {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "vault_id")]
    pub vault_id: i32,
}

impl VaultDepositHold {
    pub fn new(amount: String, asset_name: String, currency: String, vault_id: i32) -> VaultDepositHold {
        VaultDepositHold {
            amount,
            asset_name,
            currency,
            vault_id,
        }
    }
}

