/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultRequestAckResponse : Returned by `request_vault_deposit` / `request_vault_withdraw`: the id the queued request was assigned (the user's handle for polling / cancelling).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultRequestAckResponse {
    #[serde(rename = "request_id")]
    pub request_id: models::VaultRequestId,
}

impl VaultRequestAckResponse {
    /// Returned by `request_vault_deposit` / `request_vault_withdraw`: the id the queued request was assigned (the user's handle for polling / cancelling).
    pub fn new(request_id: models::VaultRequestId) -> VaultRequestAckResponse {
        VaultRequestAckResponse {
            request_id,
        }
    }
}

