/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultConfig : Configuration for a vault subaccount's deposit/withdrawal controls.  Every field is immutable after vault creation. Mutable, informational settings (descriptions, an advisory TVL cap) live in off-chain vault state, not here.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultConfig {
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "benchmark_asset", skip_serializing_if = "Option::is_none")]
    pub benchmark_asset: Option<String>,
    /// Min seconds between a holder's last deposit and their withdrawal.
    #[serde(rename = "cooldown_sec")]
    pub cooldown_sec: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "deposit_spot_asset")]
    pub deposit_spot_asset: String,
    #[serde(rename = "management_fee_bps")]
    pub management_fee_bps: i32,
    /// Max deviation of the curator's quoted share price from the mtm-derived price, both sides. Bounded at creation by the protocol-wide maximum slippage limit.
    #[serde(rename = "max_slippage_bps")]
    pub max_slippage_bps: i32,
    #[serde(rename = "performance_fee_bps")]
    pub performance_fee_bps: i32,
}

impl VaultConfig {
    /// Configuration for a vault subaccount's deposit/withdrawal controls.  Every field is immutable after vault creation. Mutable, informational settings (descriptions, an advisory TVL cap) live in off-chain vault state, not here.
    pub fn new(cooldown_sec: i32, deposit_spot_asset: String, management_fee_bps: i32, max_slippage_bps: i32, performance_fee_bps: i32) -> VaultConfig {
        VaultConfig {
            benchmark_asset: None,
            cooldown_sec,
            deposit_spot_asset,
            management_fee_bps,
            max_slippage_bps,
            performance_fee_bps,
        }
    }
}

