/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultsResponse : Returned by `public/get_vaults`: one page of vaults plus pagination info. Each row carries its subaccount id under `protocol.subaccount_id`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultsResponse {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "vaults")]
    pub vaults: Vec<models::Vault>,
}

impl VaultsResponse {
    /// Returned by `public/get_vaults`: one page of vaults plus pagination info. Each row carries its subaccount id under `protocol.subaccount_id`.
    pub fn new(pagination: models::Pagination, vaults: Vec<models::Vault>) -> VaultsResponse {
        VaultsResponse {
            pagination,
            vaults,
        }
    }
}

