/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultShareEntryResponse : One row of `get_vault_shares`: the caller's share balance in a vault plus the full enriched vault row (same shape as `public/get_vault`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultShareEntryResponse {
    /// Shares the caller holds. Same units as `vault.protocol.total_shares`.
    #[serde(rename = "shares")]
    pub shares: bigdecimal::BigDecimal,
    #[serde(rename = "vault")]
    pub vault: models::Vault,
}

impl VaultShareEntryResponse {
    /// One row of `get_vault_shares`: the caller's share balance in a vault plus the full enriched vault row (same shape as `public/get_vault`).
    pub fn new(shares: bigdecimal::BigDecimal, vault: models::Vault) -> VaultShareEntryResponse {
        VaultShareEntryResponse {
            shares,
            vault,
        }
    }
}

