/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vault {
    /// USD spot price of the HWM benchmark asset (`1.0` for feed-less USD vaults). null when a configured benchmark has no resolvable price.
    #[serde(rename = "benchmark_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub benchmark_price: Option<Option<bigdecimal::BigDecimal>>,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "curator")]
    pub curator: String,
    /// Shares held by the curator (the vault subaccount's owner) — their skin-in-the-game. Same units as `protocol.total_shares`.
    #[serde(rename = "curator_shares")]
    pub curator_shares: bigdecimal::BigDecimal,
    #[serde(rename = "description")]
    pub description: String,
    /// Optional non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits, or null; a string or JSON number is accepted
    #[serde(rename = "mtm_cap", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mtm_cap: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "name")]
    pub name: String,
    /// Live NAV expressed in the HWM benchmark asset's units. null when the vault couldn't be priced or its configured benchmark has no spot price.
    #[serde(rename = "nav_benchmark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nav_benchmark: Option<Option<bigdecimal::BigDecimal>>,
    /// Live mark-to-market NAV (USD) — signed, so an insolvent vault surfaces as a negative value. null only when the vault couldn't be priced (e.g. missing data). Divide by `protocol.total_shares` for the pre-fee share price.
    #[serde(rename = "nav_usd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nav_usd: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "protocol")]
    pub protocol: models::ProtocolVault,
    /// Live share price (USD/share) as if curator fees were settled now — the price a depositor/withdrawer faces. null when unpriceable or the vault is insolvent (a fee settlement on negative NAV is meaningless).
    #[serde(rename = "simulated_share_price_usd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub simulated_share_price_usd: Option<Option<bigdecimal::BigDecimal>>,
    #[serde(rename = "whitelist_only")]
    pub whitelist_only: bool,
}

impl Vault {
    pub fn new(curator: String, curator_shares: bigdecimal::BigDecimal, description: String, name: String, protocol: models::ProtocolVault, whitelist_only: bool) -> Vault {
        Vault {
            benchmark_price: None,
            curator,
            curator_shares,
            description,
            mtm_cap: None,
            name,
            nav_benchmark: None,
            nav_usd: None,
            protocol,
            simulated_share_price_usd: None,
            whitelist_only,
        }
    }
}

