/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultForceBurnResponse : Returned by `force_burn`: identifiers to track the on-chain `ForceBurn` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultForceBurnResponse {
    #[serde(rename = "op_uuid")]
    pub op_uuid: String,
    #[serde(rename = "operation_id")]
    pub operation_id: i32,
}

impl VaultForceBurnResponse {
    /// Returned by `force_burn`: identifiers to track the on-chain `ForceBurn` operation.
    pub fn new(op_uuid: String, operation_id: i32) -> VaultForceBurnResponse {
        VaultForceBurnResponse {
            op_uuid,
            operation_id,
        }
    }
}

