/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VaultRequestId : Composite vault request id: `(vault_subaccount_id, wallet, vault_nonce)`  Useful as a stable dedup key across off-chain and on-chain vault events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultRequestId {
    #[serde(rename = "vault_nonce")]
    pub vault_nonce: String,
    #[serde(rename = "vault_subaccount_id")]
    pub vault_subaccount_id: i32,
    /// 20-byte Ethereum address as a 0x-prefixed lowercase hex string.
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl VaultRequestId {
    /// Composite vault request id: `(vault_subaccount_id, wallet, vault_nonce)`  Useful as a stable dedup key across off-chain and on-chain vault events.
    pub fn new(vault_nonce: String, vault_subaccount_id: i32, wallet: String) -> VaultRequestId {
        VaultRequestId {
            vault_nonce,
            vault_subaccount_id,
            wallet,
        }
    }
}

