/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolFeedDataResponse {
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deadline")]
    pub deadline: i32,
    #[serde(rename = "expiry")]
    pub expiry: i32,
    #[serde(rename = "signatures")]
    pub signatures: models::OracleSignatureDataResponse,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "vol_data")]
    pub vol_data: models::VolSviParamDataResponse,
}

impl VolFeedDataResponse {
    pub fn new(confidence: String, currency: String, deadline: i32, expiry: i32, signatures: models::OracleSignatureDataResponse, timestamp: i32, vol_data: models::VolSviParamDataResponse) -> VolFeedDataResponse {
        VolFeedDataResponse {
            confidence,
            currency,
            deadline,
            expiry,
            signatures,
            timestamp,
            vol_data,
        }
    }
}

