/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolSviParamDataResponse {
    #[serde(rename = "SVI_a")]
    pub svi_a: String,
    #[serde(rename = "SVI_b")]
    pub svi_b: String,
    #[serde(rename = "SVI_fwd")]
    pub svi_fwd: String,
    #[serde(rename = "SVI_m")]
    pub svi_m: String,
    #[serde(rename = "SVI_refTau")]
    pub svi_ref_tau: String,
    #[serde(rename = "SVI_rho")]
    pub svi_rho: String,
    #[serde(rename = "SVI_sigma")]
    pub svi_sigma: String,
}

impl VolSviParamDataResponse {
    pub fn new(svi_a: String, svi_b: String, svi_fwd: String, svi_m: String, svi_ref_tau: String, svi_rho: String, svi_sigma: String) -> VolSviParamDataResponse {
        VolSviParamDataResponse {
            svi_a,
            svi_b,
            svi_fwd,
            svi_m,
            svi_ref_tau,
            svi_rho,
            svi_sigma,
        }
    }
}

