/*
 * Derive v3 API
 *
 * JSON-RPC 2.0 methods, served over WebSocket and HTTP POST.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WithdrawalEntry : `amount` and `fee` are decimal strings (e.g. `\"1.1\"`); the net sent to the recipient is `amount - fee`. `wallet` is the account owner; `recipient` is the L1 destination. `asset` is the protocol asset (the native-ETH sentinel for ETH); `erc20_address` is the on-chain ERC20 the funds settle against (WETH for native ETH). `operation_id`/`batch_uuid` are the stable uuids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalEntry {
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "amount")]
    pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "batch_status")]
    pub batch_status: models::BatchStatus,
    #[serde(rename = "batch_uuid")]
    pub batch_uuid: String,
    #[serde(rename = "erc20_address")]
    pub erc20_address: String,
    /// Non-negative decimal string of the human value (e.g. `\"1.5\"`), up to 12 fractional digits; a string or JSON number is accepted
    #[serde(rename = "fee")]
    pub fee: bigdecimal::BigDecimal,
    #[serde(rename = "operation_id")]
    pub operation_id: String,
    #[serde(rename = "recipient")]
    pub recipient: String,
    #[serde(rename = "subaccount_id")]
    pub subaccount_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "tx_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<Option<String>>,
    #[serde(rename = "wallet")]
    pub wallet: String,
}

impl WithdrawalEntry {
    /// `amount` and `fee` are decimal strings (e.g. `\"1.1\"`); the net sent to the recipient is `amount - fee`. `wallet` is the account owner; `recipient` is the L1 destination. `asset` is the protocol asset (the native-ETH sentinel for ETH); `erc20_address` is the on-chain ERC20 the funds settle against (WETH for native ETH). `operation_id`/`batch_uuid` are the stable uuids.
    pub fn new(amount: bigdecimal::BigDecimal, asset: String, batch_status: models::BatchStatus, batch_uuid: String, erc20_address: String, fee: bigdecimal::BigDecimal, operation_id: String, recipient: String, subaccount_id: i32, timestamp: i32, wallet: String) -> WithdrawalEntry {
        WithdrawalEntry {
            amount,
            asset,
            batch_status,
            batch_uuid,
            erc20_address,
            fee,
            operation_id,
            recipient,
            subaccount_id,
            timestamp,
            tx_hash: None,
            wallet,
        }
    }
}

